### PR TITLE
Correctly reset billboard position after height reference changed to none

### LINKED ISSUE #4300: Cesium crashes when changing label height reference
``` javascript
var viewer = new Cesium.Viewer('cesiumContainer', {
    baseLayerPicker: false,
    terrainProvider: new Cesium.CesiumTerrainProvider({
        url : 'https://assets.agi.com/stk-terrain/world'
    })
});

var labelCollection = viewer.scene.primitives.add(new Cesium.LabelCollection({
    scene : viewer.scene
}));

var label = labelCollection.add({
    position : Cesium.Cartesian3.fromDegrees(-110, 50),
    text: 'text',
    heightReference: Cesium.HeightReference.CLAMP_TO_GROUND
});

var clamp = true;
Sandcastle.addToolbarButton('Toggle Height Reference', function() {
    clamp = !clamp;
    var heightReference = clamp ? Cesium.HeightReference.CLAMP_TO_GROUND : Cesium.HeightReference.NONE;
    label.heightReference = heightReference;
});
```

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #4300

`Billboard` sets `label. _clampedPosition = undefined` when the height reference is changed to none.  This was then setting the label glyph billboard positions to undefined as well.  This change properly resets them to `label.position` after height reference is changed no none.

Test example:

``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');

var labelCollection = viewer.scene.primitives.add(new Cesium.LabelCollection({
    scene : viewer.scene
}));

var pos = Cesium.Cartesian3.fromDegrees(-110, 50, 1000);
var label = labelCollection.add({
    position : pos,
    text: 'text',
    heightReference: Cesium.HeightReference.CLAMP_TO_GROUND
});

var clamp = true;
Sandcastle.addToolbarButton('Toggle Height Reference', function() {
    clamp = !clamp;
    var heightReference = clamp ? Cesium.HeightReference.CLAMP_TO_GROUND : Cesium.HeightReference.NONE;
    label.heightReference = heightReference;
});

viewer.scene.camera.flyTo({
    destination: pos
});
```

### CODE REVIEW

**Comment by mramato** [comment]
I can confirm the problem is fixed and this makes sense.  Just the one comment about the test.

File: Specs/Scene/LabelCollectionSpec.js [hunk 1]
```diff
@@ -1463,6 +1463,25 @@ defineSuite([
...
+                position : position1,
+                text : 'abc'
+            });
+
+            scene.renderForSpecs();
+            var glyph = label._glyphs[0];
+            var billboard = glyph.billboard;
+            expect(billboard.position).toEqual(label.position);
+
+            label._clampedPosition = undefined;
```
Comment (hpinkos) [inline Specs/Scene/LabelCollectionSpec.js]: I tried that first, but you need to call `scene.renderForSpecs` to create the billboards and I couldn't get that to run when using a height reference

Comment (hpinkos) [inline Specs/Scene/LabelCollectionSpec.js]: more specifically, because height reference needs a globe and globe needs like a bunch of things so it doesn't crash when `Camera.update` is called

**Comment by hpinkos** [comment]
@mramato I swear I tried that exact same thing earlier and it didn't work.  I don't know what I did wrong, haha.

Thanks!  That should be fixed now.

**Comment by mramato** [comment]
Sure, sure 😉
