### PR TITLE
Documentation fixes

### LINKED ISSUE #3827: createMesh in documentation
If `TerrainMesh` has been removed from the public API, shouldn't the same be done for the `createMesh` methods on `TerrainData` (`HeightmapTerrainData` and `QuantizedMeshTerrainData`)?

### PR DESCRIPTION
**Pull request by slozier**
Also resolves #3827.

### CODE REVIEW

File: Source/Core/HeightmapTerrainData.js [hunk 1]
```diff
@@ -82,13 +82,11 @@ define([
      * var heightBuffer = new Uint16Array(buffer, 0, that._heightmapWidth * that._heightmapWidth);
      * var childTileMask = new Uint8Array(buffer, heightBuffer.byteLength, 1)[0];
      * var waterMask = new Uint8Array(buffer, heightBuffer.byteLength + 1, buffer.byteLength - heightBuffer.byteLength - 1);
-     * var structure = Cesium.HeightmapTessellator.DEFAULT_STRUCTURE;
```
Comment (hpinkos) [inline Source/Core/HeightmapTerrainData.js]: Why did you remove this?

**Comment by hpinkos** [comment]
Thanks @slozier!  I just had that one question, but the other changes look good

File: Source/Core/HeightmapTerrainData.js (hunk 1 above)
Comment (slozier) [inline Source/Core/HeightmapTerrainData.js]: `HeightmapTessellator` was removed from the public API.
