### PR TITLE
Billboard depth fail

### LINKED ISSUE #5121: Disable depth test for labels close to the viewer
It may be desirable to always have a label be visible, e.g. attached to building or model, when the viewer is close. For example, a label at the center of the milk truck model should be visible at any angle. Now, the depth test on labels causes parts of the label to be occluded.

One option is to have two batches of billboards, one with the depth test enabled and the other would have it disabled. Billboards would need to be rebatched every time the camera moves.

Another option is to move the billboard positions in clip space to the near plane in the vertex shader. Here is an example that works pretty well when added to the end of `BillboardCollectionVS.glsl`:
```glsl
float len = length(positionEC.xyz);
if (len > 0.0 && len < 10000.0 && gl_Position.z > -gl_Position.w && gl_Position.z < gl_Position.w) {
    gl_Position.z = -gl_Position.w;
}
```

The distance `10000.0` should be replaced by a uniform or per-vertex attribute.

### PR DESCRIPTION
**Pull request by bagnell**
Adds `disableDepthDistance` and `alwaysDisableDepth` properties to labels/billboards/points. `alwaysDisableDepth` will always draw the billboard in front of everything. `disableDepthDistance` will always draw the billboard when the distance to the camera is less than that `disableDepthDistance`.

Fixes #5121.

- [x] Add doc
- [x] Add tests
- [x] Update CHANGES.md

### CODE REVIEW

**Comment by pjcozzi** [comment]
Fixes #5121

**Comment by pjcozzi** [comment]
Also fixes #2694

**Comment by pjcozzi** [comment]
For the API and naming, perhaps just:
* `disableDepthTestDistance` with a default of `0.0`.

When it's `Number.POSITIVE_INFINITY`, depth is never tested.  When `0.0`, it is always tested.

File: Source/Scene/Billboard.js [hunk 1]
```diff
@@ -178,7 +180,9 @@ define([
     var TRANSLUCENCY_BY_DISTANCE_INDEX = Billboard.TRANSLUCENCY_BY_DISTANCE_INDEX = 12;
     var PIXEL_OFFSET_SCALE_BY_DISTANCE_INDEX = Billboard.PIXEL_OFFSET_SCALE_BY_DISTANCE_INDEX = 13;
     var DISTANCE_DISPLAY_CONDITION = Billboard.DISTANCE_DISPLAY_CONDITION = 14;
-    Billboard.NUMBER_OF_PROPERTIES = 15;
+    var DISABLE_DEPTH_DISTANCE = Billboard.DISABLE_DEPTH_DISTANCE = 15;
+    var ALWAYS_DISABLE_DEPTH = Billboard.ALWAYS_DISABLE_DEPTH = 16;
+    Billboard.NUMBER_OF_PROPERTIES = 17;
```
Comment (pjcozzi) [inline Source/Scene/Billboard.js]: Do you have ideas for avoiding going above 16 attributes?

Comment (pjcozzi) [inline Source/Scene/Billboard.js]: Nevermind, I see that we are good.

File: Source/Scene/PointPrimitive.js [hunk 2]
```diff
@@ -100,7 +102,9 @@ define([
     var PIXEL_SIZE_INDEX = PointPrimitive.PIXEL_SIZE_INDEX = 5;
     var SCALE_BY_DISTANCE_INDEX = PointPrimitive.SCALE_BY_DISTANCE_INDEX = 6;
     var TRANSLUCENCY_BY_DISTANCE_INDEX = PointPrimitive.TRANSLUCENCY_BY_DISTANCE_INDEX = 7;
-    var DISTANCE_DISPLAY_CONDITION_INDEX = PointPrimitive.DISTANCE_DISPLAY_CONDITION = 8;
+    var DISTANCE_DISPLAY_CONDITION_INDEX = PointPrimitive.DISTANCE_DISPLAY_CONDITION_INDEX = 8;
+    var DISABLE_DEPTH_DISTANCE_INDEX = PointPrimitive.DISABLE_DEPTH_DISTANCE_INDEX = 15;
```
Comment (pjcozzi) [inline Source/Scene/PointPrimitive.js]: Why 15 and 16?  Not 9 and 10?

File: Source/Shaders/BillboardCollectionVS.glsl [hunk 3]
```diff
@@ -3,13 +3,13 @@ attribute vec2 direction;
...
-attribute vec4 scaleByDistance;             // near, nearScale, far, farScale
-attribute vec4 pixelOffsetScaleByDistance;  // near, nearScale, far, farScale
-attribute vec2 distanceDisplayCondition;    // near, far
+attribute vec4 compressedAttribute0;                       // pixel offset, translate, horizontal origin, vertical origin, show, direction, texture coordinates (texture offset)
+attribute vec4 compressedAttribute1;                       // aligned axis, translucency by distance, image width
+attribute vec4 compressedAttribute2;                       // image height, color, pick color, size in meters, valid aligned axis, 13 bits free
+attribute vec4 eyeOffset;                                  // eye offset in meters, 4 bytes free (texture range)
+attribute vec4 scaleByDistance;                            // near, nearScale, far, farScale
+attribute vec4 pixelOffsetScaleByDistance;                 // near, nearScale, far, farScale
+attribute vec4 distanceDisplayConditionAndDisableDepth;    // near, far, disableDepthDistance, alwaysDisableDepth
```
Comment (pjcozzi) [inline Source/Shaders/BillboardCollectionVS.glsl]: Could `alwaysDisableDepth` be the sign of `disableDepthDistance`?

File: Source/Shaders/BillboardCollectionVS.glsl [hunk 4]
```diff
@@ -246,8 +246,8 @@ void main()
 #endif
 
 #ifdef DISTANCE_DISPLAY_CONDITION
-    float nearSq = distanceDisplayCondition.x * distanceDisplayCondition.x;
-    float farSq = distanceDisplayCondition.y * distanceDisplayCondition.y;
+    float nearSq = distanceDisplayConditionAndDisableDepth.x * distanceDisplayConditionAndDisableDepth.x;
```
Comment (pjcozzi) [inline Source/Shaders/BillboardCollectionVS.glsl]: Unrelated to this PR, but why don't we store the squared distance in the vertex attribute to avoid this computation?

**Comment by denverpierce** [comment]
Is it possible to get this somewhere higher in the API, like dataSources or viewer/scene? Label clipping issues especially have been a pain point, and I don't see an issue overriding labels especially to never depth test.

**Comment by Zizekftw** [comment]
Seconded @denverpierce's comment. We load pins from KML files with label clipping.

**Comment by pjcozzi** [comment]
@bagnell what do you think of a min distance on `Scene` that could set a `czm_` uniform for @denverpierce and @Zizekftw's request?

**Comment by bagnell** [comment]
> @bagnell what do you think of a min distance on Scene that could set a czm_ uniform for @denverpierce  and @Zizekftw's request?

Added in e990328

File: Source/Shaders/BillboardCollectionVS.glsl (hunk 4 above)
Comment (bagnell) [inline Source/Shaders/BillboardCollectionVS.glsl]: Not sure, updated here: 18b6769

**Comment by bagnell** [comment]
@pjcozzi This is ready for another look.

File: Source/Shaders/BillboardCollectionVS.glsl [hunk 5]
```diff
@@ -258,6 +258,24 @@ void main()
     gl_Position = czm_viewportOrthographic * vec4(positionWC.xy, -positionWC.z, 1.0);
     v_textureCoordinates = textureCoordinates;
 
+#ifdef DISABLE_DEPTH_DISTANCE
+    float disableDepthTestDistance = distanceDisplayConditionAndDisableDepth.z;
+    if (disableDepthTestDistance == 0.0 && czm_minimumDisableDepthTestDistance != 0.0) {
```
Comment (pjcozzi) [inline Source/Shaders/BillboardCollectionVS.glsl]: Put `{` on a new line in GLSL.

File: Source/Shaders/BillboardCollectionVS.glsl [hunk 6]
```diff
@@ -258,6 +258,24 @@ void main()
...
+        disableDepthTestDistance = czm_minimumDisableDepthTestDistance;
+    }
+
+    if (disableDepthTestDistance != 0.0) {
+        gl_Position.z = min(gl_Position.z, gl_Position.w);
+
+        bool clipped = gl_Position.z < -gl_Position.w || gl_Position.z > gl_Position.w;
+        float distance = length(positionEC.xyz);
+        if (!clipped && (disableDepthTestDistance < 0.0 || (distance > 0.0 && distance < disableDepthTestDistance)))
```
Comment (pjcozzi) [inline Source/Shaders/BillboardCollectionVS.glsl]: I might have already asked this, but should be store squared distance instead to avoid the `length` above?  Or are you concerned about overflow?  We would treat infinity as a special case.

**Comment by pjcozzi** [comment]
Add this to a Sandcastle example.

**Comment by pjcozzi** [comment]
@bagnell feel free to push this 1.33, up to you.

**Comment by pjcozzi** [comment]
@tfili @mramato does it make sense to use this by default for KML when ground clamping is used?

**Comment by denverpierce** [comment]
Google Earth doesn't depth test labels, but it does test icons.

**Comment by bagnell** [comment]
@pjcozzi This is ready for another look.

File: Source/Shaders/BillboardCollectionVS.glsl (hunk 6 above)
Comment (bagnell) [inline Source/Shaders/BillboardCollectionVS.glsl]: You asked about it for the distance display conditions, which I fixed, but somehow forgot this. It's been updated.

**Comment by pjcozzi** [comment]
All looks good.

Please also merge into `3d-tiles`.
