### PR TITLE
Fix billboard on terrain and Globe.getHeight

### LINKED ISSUE #4598: Clamping billboards to terrain - inaccurate positioning
Hi,
Recently I encountered a problem with clamping billborads to terrain.
Clamped billboards are appearing with an offset of few meters (not a fixed offset).

In order to see this problem you can enter the following sandcastle example.
When you click `toggle terrain` button you will see the billboard (on the terrain). Click it again (turn the terrain off) and you will see it with some offset.

#### Sandcastle:

http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases&gist=9a739769ae5f781db3ad3eed90c7cdb8

(I had to add the billboard again in the code since billboards are disappearing when terrain is toggled. Is it a known problem or should I open another issue for it?).

 
I looked at the code and found a point that could cause this problem, but since **I am not experienced in this field** I want you to confirm it.

Cesium uses geocentric normal when it calculates the (wrong) updated position.
You can see it [here](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.26/Source/Scene/QuadtreePrimitive.js#L636)

However when I use geodetic surface normal in this calculation the result is acccuarte.

The following sandcastle example illustrates the difference between the two methods.
Run it and wait until tiles are fully loaded.
Then click `'Place Billboards On Terrain'` button.

Three billboards should appear on the map: 
Yellow billboard position is calculated with the current method.
Red billboard position is calculated with the GeodeticSurfaceNormal.
The green billboard is just a conversion of the original cartographic, with current terrain height, to cartesian.

The green billboard (cartographic to cartesian) and the red (GeodeticSurfaceNormal) should appear at the same position, so I made a **pixel offset** to the green billboard.

You can pick a billboard to see by which method it was created.

#### Sandcastle

http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases&gist=8caeac6aa77715993dff4bf20addc806

You may wonder why the third result's **height** (green- cartographich to cartesian) is not exactly the same as the geodeticSurfaceNormal  (red) **height**.
A quick look at the code in Globe.getHeight shows that it suffers from the same problem - it uses geocentric normal rather than surface normal.
As a result, the intersection point from which it extracts the height is different and hence the wrong result.

You can see the fixed code [here](https://github.com/duvifn/cesium/blob/fix_billboardOnTerrain/Source/Scene/QuadtreePrimitive.js#L634) ,
and [here](https://github.com/duvifn/cesium/blob/fix_billboardOnTerrain/Source/Scene/Globe.js#L433) .
I can do a pull request for that if you think it's  correct...

### PR DESCRIPTION
**Pull request by duvifn**
fix #4598 and #3411

### CODE REVIEW

**Comment by duvifn** [comment]
I had a typo in the commit message (`Globe.pick` instead  of `Globe.getHeight`). So I made `commit --amned` and now it's ready

**Comment by mramato** [comment]
Thanks @duvifn!  This bug has been on my wish list for quite some time.  @bagnell can you please review and merge, we already have a CLA.

File: Source/Scene/Globe.js [hunk 1]
```diff
@@ -430,7 +430,16 @@ define([
         var cartesian = ellipsoid.cartographicToCartesian(cartographic, scratchGetHeightCartesian);
 
         var ray = scratchGetHeightRay;
-        Cartesian3.normalize(cartesian, ray.direction);
+        var surfaceNormal = ellipsoid.geodeticSurfaceNormal(cartesian, ray.direction);
+
+        // compute origin point, to account for a case where the terrain is under ellipsoid surface
+        var minimumHeight = Math.min(defaultValue(tile.data.minimumHeight, 0.0), 0.0);
```
Comment (duvifn) [inline Source/Scene/Globe.js]: Do you think it would be safer to use lower value instead of `0.0` in `defaultValue(tile.data.minimumHeight, 0.0)`?
for example `-11500.0` (taken from [here](https://github.com/duvifn/cesium/blob/fix_billboardOnTerrain/Source/Scene/QuadtreePrimitive.js#L648))

**Comment by bagnell** [comment]
This looks good to me. Just that one comment.

**Comment by pjcozzi** [comment]
Also, please update CHANGES.md.

**Comment by duvifn** [comment]
Thanks @bagnell!

>  Is there a reason you didn't use Cartesian3.ZERO

A ray from `Cartesian3.ZERO` with `Surface Normal` as a direction doesn't pass through the given cartographic:

> [The normal at a point on the surface of an ellipsoid does not pass through the centre, except for points on the equator or at the poles](https://en.wikipedia.org/wiki/Latitude#Geodetic_and_geocentric_latitudes)


Anyway, I discussed this problem with Omer Bar from [Survey Of Israel](http://mapi.gov.il/en/Pages/default.aspx)/Geodesy department and he suggested to use the intersection point of the `Surface Normal` with z axis (`x = 0 , y = 0, z = <varying value>`).
Ellipsoid is a [surface of revolution](http://www.springer.com/cda/content/document/cda_downloaddocument/9783319117720-c2.pdf?SGWID=0-0-45-1494952-p177003231), so surface normal intersects the axis of rotation.  

Theoretically, the intersection point can be outside the ellipsoid though I really tried but didn't get such result.
Anyway, for any of such edge cases, we can check if `abs(z)` is less than `ellipsoid.minimumRadius` with some buffer. If it's outside the ellipsoid we can use the min of `tile.minimumHeight / -11500` .

If you want to see how this intersection point behaves, see this [sandcastle example](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases&gist=6512fe368206f2fa5b1bd707ea855061) that shows how this point  is changed relative to the normal.
The label is the intersection point's values, the arrow is the surface normal.
Click `Toggle animation` to start.
rotation_axis_intersection

Do you see any problem with this approach?
If no, 
I changed the code according to this suggestion. Can you to review it?


BTW, 
I suspect (not certain, though) that some strange behavior of the camera under terrain (#4680, #4660) should be improved with this PR since `Camera.prototype._adjustHeightForTerrain` uses `Globe.getHeight` (that currently returns a wrong result or undefined near the surface).

**Comment by duvifn** [comment]
I changed the code a bit according to @pjcozzi 's suggestion in #4682.
Now cartesian is computed on the ellipsoid surface.

@bagnell, I didn't find any other usage of `data.position` (changed to `data.positionOnEllipsoidSurface`) in the code that could be impacted by this change, but it's possible I missed something.

This is ready for review.

File: Source/Scene/Globe.js [hunk 2]
```diff
@@ -424,10 +426,44 @@ define([
...
+            magnitude = cartesian.z / surfaceNormal.z;
+        } else { //(0,0,0), just for case
+            magnitude = 0;
+        }
+
+        var vectorToMinimumPoint = Cartesian3.multiplyByScalar(surfaceNormal, magnitude, scratchGetHeightIntersection);
+        Cartesian3.subtract(cartesian, vectorToMinimumPoint, ray.origin);
+
+        // Theoretically, the intersection point can be outside the ellipsoid, so we have to check if the result's 'z' is inside the ellipsoid (with some buffer)
+        if (Math.abs(ray.origin.z) >= ellipsoid.radii.z -11500.0){
```
Comment (pjcozzi) [inline Source/Scene/Globe.js]: Instead of hard coding `-11500.0` here and below, can this use some percentage of [ellipsoid.radii.maximumComponent](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Cartesian3.js#L280)?  Or does the buffer need to be this big?  Instead, can it be a much smaller epsilon?

File: Source/Scene/QuadtreePrimitive.js [hunk 3]
```diff
@@ -761,13 +761,46 @@ define([
...
-                        data.position = ellipsoid.cartographicToCartesian(data.positionCartographic);
+                    if (!defined(data.positionOnEllipsoidSurface)) {
+                        // cartesian has to be on the ellipsoid surface for `ellipsoid.geodeticSurfaceNormal`
+                        data.positionOnEllipsoidSurface = Cartesian3.fromRadians(data.positionCartographic.longitude, data.positionCartographic.latitude, 0.0, ellipsoid);
                     }
 
                     if (mode === SceneMode.SCENE3D) {
-                        Cartesian3.clone(Cartesian3.ZERO, scratchRay.origin);
-                        Cartesian3.normalize(data.position, scratchRay.direction);
+                        var surfaceNormal = ellipsoid.geodeticSurfaceNormal(data.positionOnEllipsoidSurface, scratchRay.direction);
```
Comment (pjcozzi) [inline Source/Scene/QuadtreePrimitive.js]: Does this duplicate code belong in a utility function for `Ray` or `Ellipsoid`?  That would also be more testable so we could add unit tests.

**Comment by bagnell** [comment]
>A ray from Cartesian3.ZERO with Surface Normal as a direction doesn't pass through the given cartographic

Ah, of course. I can't see anything wrong with your new approach. This looks good to me. @pjcozzi can merge when this is ready.

**Comment by duvifn** [comment]
Hi,
Thanks for reviewing this.

> Instead of hard coding -11500.0 here and below, can this use some percentage of ellipsoid.radii.maximumComponent? Or does the buffer need to be this big? Instead, can it be a much smaller epsilon?

This value was taken from cesium code, [here](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.27/Source/Scene/QuadtreePrimitive.js#L640).

@bagell wrote about this value: 
> I would use -11500.0. For the lowest resolution terrain tiles, triangle vertices may be near the ellipsoid surface, but the interiors cutting through the ellipsoid will drop to around this height.

For this value to be be calculated accurately we need:
    1) width/height of tiles at the lowest level.
    2) ellipsoid dimensions
    3) terrain provider minimum possible value
It is also important to compute this value only once in the terrain provider initialization so we wouldn't have to calculate it every time we do some operations.

To make it possible we have to do some code refactoring, and I believe that this is out of the scope of this PR.
I think @bagnell [wrote](https://github.com/AnalyticalGraphicsInc/cesium/blob/1.27/Source/Scene/QuadtreePrimitive.js#L639) the following comment in the code because of the above reasons:
>   // minimum height for the terrain set, need to get this information from the terrain provider

Anyway, for **Earth datums** all of this is not needed since the intersection point with the `z-axis` would always be very close to Cartesian3.ZERO.

After I tested it practically, I asked a mathematician colleague to prove that formally and I put here the proof for that (I had to upload it as a pictures because MD doesn't support latex).





For Earth (WGS84 ellipsoid), the absolute value of this constant is 0.00673 (i.e. point is always very close to Cartesian3.ZERO);

For [Moon](https://en.wikipedia.org/wiki/Moon), according to wikipedia values, the constant is 0.0024.

I don't really know other shapes of planetary bodies that cesium might represent in the future, hence there is the fallback we discussed above.

> Does this duplicate code belong in a utility function for Ray or Ellipsoid? That would also be more testable so we could add unit tests.

I added `Ellipsoid.prototype.getSurfaceNormalIntersectionWithZAxis` function with a bit optimized code (multiply only the `z` by a constant instead of some vector operations), and wrote specs for it.

This is ready.

**Comment by duvifn** [comment]
Changed a bit.
This is ready.

**Comment by duvifn** [comment]
Minor changes.
This is ready.

CC: @pjcozzi @bagnell

File: Source/Core/Ellipsoid.js [hunk 4]
```diff
@@ -608,5 +613,55 @@ define([
...
+     *
+     * @exception {DeveloperError} position is required.
+     * @exception {DeveloperError} Ellipsoid must be an ellipsoid of revolution (radii.x == radii.y).
+     * @exception {DeveloperError} Ellipsoid.radii.z must be greater than 0.
+     */
+
+    Ellipsoid.prototype.getSurfaceNormalIntersectionWithZAxis = function(position, buffer, result) {
+
+        //>>includeStart('debug', pragmas.debug);
+        if (!defined(position)) {
```
Comment (pjcozzi) [inline Source/Core/Ellipsoid.js]: Really minor, but could you please add unit tests for these three `DeveloperError` cases?

**Comment by pjcozzi** [comment]
Thanks for the updates, @duvifn!

I made some trivial style tweaks for consistency with the rest of the Cesium codebase.  Let me know when you add those other unit tests (it will be easy) and we'll merge this.  If we merge it early next week, it will ship in Cesium 1.29 on January 2.

**Comment by duvifn** [comment]
Hi @pjcozzi !

Did you mean [these specs](https://github.com/duvifn/cesium/blob/fix_billboardOnTerrain/Specs/Core/EllipsoidSpec.js#L437)? (already there),
Or I didn't correctly understand you?

**Comment by pjcozzi** [comment]
Ah yes, great!

Thanks again for this contribution!
