### PR TITLE
Fixed Kml features to respect timespan and timestamp of their parent containers

### LINKED ISSUE #4041: KML timespan tag issue
Reported on the forum: https://groups.google.com/d/msg/cesium-dev/UrMK4Fku_Gk/Q-d6UmuRBAAJ
All of the images appear at once instead of following the timespan they are associated with

See the post for a link to the kmz file

### PR DESCRIPTION
**Pull request by tfili**
Also added tests and updated `CHANGES.md`

Fixes #4041.

### CODE REVIEW

**Comment by hpinkos** [comment]
Great @tfili, thanks!

File: Source/DataSources/KmlDataSource.js [hunk 1]
```diff
@@ -2575,6 +2597,15 @@ define([
                 var newEntity = newEntities[i];
                 if (!defined(newEntity.parent)) {
                     newEntity.parent = networkLinkEntity;
+
+                    if (defined(networkLinkAvailability)) {
```
Comment (mramato) [inline Source/DataSources/KmlDataSource.js]: @tfili  You have essentially the same block of code copy and pasted 3 times, can you please turn this into a helper function instead.
