### PR TITLE
fix classification type not getting propagated properly for dynamic entities on terrain

### LINKED ISSUE #6606: Rectangle sandcastle example broken in master
http://localhost:8080/Apps/Sandcastle/index.html?src=Rectangle.html&label=Geometries

@likangning93 this is from your materials on ground primitives changes

### PR DESCRIPTION
**Pull request by likangning93**
Fixes #6606

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@likangning93, thanks for the pull request! Maintainers, we have a signed CLA from @likangning93, so you can review this at any time.

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
Can we easily add a unit test here?

@hpinkos please review/merge when happy.  Thanks to both of you!

**Comment by hpinkos** [comment]
@likangning93 yeah, can you add a test to `createGeometryUpdaterGroundGeometrySpecs`?  It should be similar to the `dynamic updater on terrain` test, just check the value is being set on the primitive added to `groundPrimitives`

**Comment by likangning93** [comment]
@hpinkos ready!

File: Specs/createGeometryUpdaterGroundGeometrySpecs.js [hunk 1]
```diff
@@ -154,6 +156,24 @@ define([
             dynamicUpdater.destroy();
             updater.destroy();
         });
+
+        it('dynamic updater on terrain propagates classification type', function() {
+            var entity = createDynamicEntity();
```
Comment (hpinkos) [inline Specs/createGeometryUpdaterGroundGeometrySpecs.js]: Instead of setting `classificationType` in each of the `XXXGeometryUpdaterSpec` files, do `entity[geometryPropertyName].classificationType = ClassificationType.BOTH` in this file

**Comment by likangning93** [comment]
@hpinkos updated

**Comment by hpinkos** [comment]
Perfect, thanks @likangning93!
