### PR TITLE
Remove floating-point texture requirement

### LINKED ISSUE #4563: Android: FLOATING POINT TEXTURE EXTENSION IS REQUIRED BUT NOT SUPPORTED.
It appears that loading data gives the following error:

RUNTIMEERROR: THE FLOATING POINT TEXTURE EXTENSION IS REQUIRED BUT NOT SUPPORTED.

I have a Samsung Galaxy S7. I've tried multiple browsers aswell but it keeps failing. The same javascript has no errors on pc browser.

### PR DESCRIPTION
**Pull request by bagnell**
Add falling back to packing floats into unsigned byte texture when floating point textures aren't supported.

Fixes #4563.

### CODE REVIEW

**Comment by bagnell** [comment]
I tested this on my Galaxy S6. Most newer devices with OpenGL ES 3.0 or older devices that do not have the OES_texture_float extension will reproduce the issue.

**Comment by pjcozzi** [comment]
@bagnell is there anything duplicate here that can be moved to a shared private utility file?

**Comment by pjcozzi** [comment]
Can you also add a code comment about how this is a fallback and has some cases that are not memory efficient as we discussed offline?

File: Source/Scene/BatchTable.js [hunk 1]
```diff
@@ -169,6 +183,134 @@ define([
...
+
+        var currentOffset = 0;
+        var attributesLength = attributes.length;
+        for (var i = 0; i < attributesLength; ++i) {
+            var attribute = attributes[i];
+            var componentDatatype = attribute.componentDatatype;
+
+            offsets[i] = currentOffset;
+
+            if (componentDatatype !== ComponentDatatype.UNSIGNED_BYTE && packFloats) {
```
Comment (pjcozzi) [inline Source/Scene/BatchTable.js]: It would be cleaner to do this check outside of the loop to assign to a `stride` variable then here just do: `currentOffset  += stride;`

**Comment by pjcozzi** [comment]
@bagnell I can do a final test and merge tomorrow morning before the release.  Let me know when this is updated.

**Comment by bagnell** [comment]
>@bagnell is there anything duplicate here that can be moved to a shared private utility file?

The packing/unpacking code is similar to packing elsewhere but the only thing that would be shared is the constants.

File: Source/Scene/BatchTable.js (hunk 1 above)
Comment (bagnell) [inline Source/Scene/BatchTable.js]: That would increase the memory even more. If the type is unsigned byte, we still only use one texel, but, if its a larger type, then we pack into unsigned bytes which is 4 texels.

Comment (bagnell) [inline Source/Scene/BatchTable.js]: Not all attributes will have the same component type.

File: Source/Scene/BatchTable.js [hunk 2]
```diff
@@ -349,13 +504,34 @@ define([
...
                '    return vec2(centerX + (xId * stepX), 1.0 - (centerY + (yId * stepY))); \n' +
                '} \n';
     }
 
+    function getGlslUnpackFloat(batchTable) {
+        if (!batchTable._packFloats) {
+            return '';
+        }
+
+        return 'float unpackFloat(vec4 value) \n' +
```
Comment (bagnell) [inline Source/Scene/BatchTable.js]: I wouldn't move this because it mirrors `unpackFloat`. If we could use the packing/unpacking code elsewhere, I'd be OK with it. Can you think of another case where we would do something like this?

**Comment by bagnell** [comment]
@pjcozzi This is ready unless you want me to separate out the packing code.

File: Source/Scene/BatchTable.js (hunk 1 above)
Comment (pjcozzi) [inline Source/Scene/BatchTable.js]: Ah I missed that.

File: Source/Scene/BatchTable.js (hunk 2 above)
Comment (pjcozzi) [inline Source/Scene/BatchTable.js]: Seems like anywhere we need to emulate float textures, but this is not important enough to hold up the release.

**Comment by pjcozzi** [comment]
Thanks @bagnell.

Can you merge `master` to `3d-tiles` and fix all the calls to the `BatchTable` constructor?
