### PR TITLE
Deprecate MIDDLE_DOUBLE_CLICK and RIGHT_DOUBLE_CLICK events

### LINKED ISSUE #2631: ScreenSpaceEventType.RIGHT_DOUBLE_CLICK does not work
As noted in [this forum post](https://groups.google.com/d/msg/cesium-dev/0f_KD1InXyE/pbMuKz2dxxAJ).  We should either fix this or do as we've talked about in the past and deprecate `ScreenSpaceEventHandler` since it adds nothing to the public API (and recommend users just use standard mouse events).

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes #2631

### CODE REVIEW

File: Source/Widgets/Viewer/Viewer.js [hunk 1]
```diff
@@ -703,7 +703,7 @@ Either specify options.terrainProvider instead or set options.baseLayerPicker to
         }
 
         cesiumWidget.screenSpaceEventHandler.setInputAction(pickAndSelectObject, ScreenSpaceEventType.LEFT_CLICK);
-        cesiumWidget.screenSpaceEventHandler.setInputAction(pickAndTrackObject, ScreenSpaceEventType.LEFT_DOUBLE_CLICK);
+        cesiumWidget.screenSpaceEventHandler.setInputAction(pickAndTrackObject, ScreenSpaceEventType.MIDDLE_CLICK);
```
Comment (lilleyse) [inline Source/Widgets/Viewer/Viewer.js]: I figure this will be the biggest breaking change. If this is commonly used it may be ok to keep LEFT_DOUBLE_CLICK.

Comment (emackey) [inline Source/Widgets/Viewer/Viewer.js]: Keeping `LEFT_DOUBLE_CLICK` is fine for desktop.  For UX purposes, remember neither it nor single-middle-click is available on touch devices.  Double-middle-click and double-right-click should both be completely deprecated, as browser support is weak and even desktop users don't think to try them.

Comment (lilleyse) [inline Source/Widgets/Viewer/Viewer.js]: Sound good, I'll make the corrections tomorrow.

**Comment by lilleyse** [comment]
Updated.

File: CHANGES.md [hunk 2]
```diff
@@ -5,7 +5,7 @@ Change Log
 * Deprecated
     * The properties `url` and `key` will be removed from `GeocoderViewModel` in 1.31. These properties will be available on geocoder services that support them, like `BingMapsGeocoderService`.
     * The function `createBinormalAndBitangent` of `GeometryPipeline` will be removed in 1.31. Use the function `createTangentAndBitangent` instead. [#4856](https://github.com/AnalyticalGraphicsInc/cesium/pull/4856)
-    * The enums `LEFT_DOUBLE_CLICK`, `MIDDLE_DOUBLE_CLICK`, and `RIGHT_MIDDLE_CLICK` from `ScreenSpaceEventType` have been deprecated and will be removed  in 1.31. [#2631](https://github.com/AnalyticalGraphicsInc/cesium/issues/2631)
+    * The enums `MIDDLE_DOUBLE_CLICK` and `RIGHT_MIDDLE_CLICK` from `ScreenSpaceEventType` have been deprecated and will be removed  in 1.31. [#4910](https://github.com/AnalyticalGraphicsInc/cesium/pull/4910)
```
Comment (emackey) [inline CHANGES.md]: `RIGHT_MIDDLE_CLICK` ?

Comment (lilleyse) [inline CHANGES.md]: Ah... fixed.
