### PR TITLE
fixes #5943 geocoder selects wrong list item with key press

### LINKED ISSUE #5943: Geocoder selects wrong list item with key press
In Cesium Viewer, type "3330 Walnut Street" into the Geocoder, three list items appear with autocomplete:

image

If you click on the second address - the one in Philadelphia - it zooms to the right location.

Instead, if you use the down arrow key to select the Philadelphia address and hit enter, it zooms to the first location in WI.

### PR DESCRIPTION
**Pull request by SelimAbidin**
Search command in `Source/Widgets/Geocoder/GeocoderViewModel.js ` hides suggestions first and then tries to activate the selected item which is already defined `undefined`

Moving `hideSuggestions` under `activateSuggestion` will have no impact since `activateSuggestion'` also calls it.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
[Please sign the CLA before we review this PR.](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)

Welcome to the Cesium community @SelimAbidin!

Can you please send in a [Contributor License Agreement](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) so that we can review and merge this pull request?

:warning: I noticed that [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) has not been updated. If this change updates the public API in any way, fixes a bug, or makes any non-trivial update, please add a bullet point to `CHANGES.md` and comment on this pull request so we know it was updated. For more info, see the [Pull Request Guidelines]( https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines).

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

File: Source/Widgets/Geocoder/GeocoderViewModel.js [hunk 1]
```diff
@@ -80,12 +80,12 @@ define([
         });
 
         this._searchCommand = createCommand(function() {
-            that.hideSuggestions();
             that._focusTextbox = false;
             if (defined(that._selectedSuggestion)) {
                 that.activateSuggestion(that._selectedSuggestion);
                 return false;
             }
+            that.hideSuggestions();
```
Comment (emackey) [inline Source/Widgets/Geocoder/GeocoderViewModel.js]: Was originally concerned about moving this after an early return, but, `activateSuggestion` calls this already, so this is actually the correct location for this.

**Comment by emackey** [comment]
Updated CHANGES.md in 27404a4c517.
