### PR TITLE
Reduce number of varyings for BillboardCollection

### LINKED ISSUE #6793: label : HeightReference.CLAMP_TO_GROUND  "An error occurred while rendering."
Today I update cesium 1.47 instaed 1.43.
But when I add a label with "heightReference: Cesium.HeightReference.CLAMP_TO_GROUND", the chrome reports me the text : 

An error occurred while rendering. Rendering has stopped.
RuntimeError: Program failed to link.  Link log: Could not pack varying v_logZ
Note: Additional non-conformant packing restrictions are enforced on D3D9.

Error
    at new t (http://localhost:5000/libs/Cesium/1.47/Cesium.js:451:28517)
    at f (http://localhost:5000/libs/Cesium/1.47/Cesium.js:480:17965)
    at y (http://localhost:5000/libs/Cesium/1.47/Cesium.js:480:19679)
    at d._bind (http://localhost:5000/libs/Cesium/1.47/Cesium.js:480:20694)
    at G (http://localhost:5000/libs/Cesium/1.47/Cesium.js:508:913)
    at k.draw (http://localhost:5000/libs/Cesium/1.47/Cesium.js:508:4878)
    at n.execute (http://localhost:5000/libs/Cesium/1.47/Cesium.js:479:21080)
    at Ge (http://localhost:5000/libs/Cesium/1.47/Cesium.js:530:16825)
    at Xe (http://localhost:5000/libs/Cesium/1.47/Cesium.js:530:21309)
    at tt (http://localhost:5000/libs/Cesium/1.47/Cesium.js:530:26613)

my test code:
``` javascript
var viewer = new Cesium.Viewer('cesiumContainer', {
    terrainProvider: Cesium.createWorldTerrain()
});
viewer.scene.globe.depthTestAgainstTerrain = true;

var e = viewer.entities.add({
    position : Cesium.Cartesian3.fromDegrees(-122.1958, 46.1915),
     label : {
        text : 'Clamped to ground',
        heightReference : Cesium.HeightReference.CLAMP_TO_GROUND,
        horizontalOrigin : Cesium.HorizontalOrigin.CENTER,
        verticalOrigin : Cesium.VerticalOrigin.BOTTOM,
        fillColor : Cesium.Color.BLACK,
        showBackground : true,
        backgroundColor : new Cesium.Color(1, 1, 1, 0.7),
        backgroundPadding : new Cesium.Cartesian2(8, 4)
    }
});

viewer.trackedEntity = e;
```

### PR DESCRIPTION
**Pull request by hpinkos**
Fixes #6793  (i think)

When doing the billboard depth test in the fragment shader, we were using more varyings than are supported on older video cards.

I think reducing the number of varyings by 1 will fix the cases reported.  

@bagnell I'm still trying to understand how this was using more varyings than supported.  The webglreport in #6793 says `Max Varying Vectors: 9` and we were using 8 in `BillboardCollection` and `vertexLogDepth` uses... 2?  It uses a `float` and a `vec3` varying.  Does this count as 1 or 2?  Should we change it to be 1 `vec4`?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @hpinkos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/fix-billboard-varying/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by bagnell** [comment]
> It uses a float and a vec3 varying. Does this count as 1 or 2?

It counts as 2.

>Should we change it to be 1 vec4?

Yes. The other option is to put it in a `#ifdef` since it's only used by shadows for now.

**Comment by hpinkos** [comment]
@bagnell updated.  I changed log depth to use one `vec4`

**Comment by bagnell** [comment]
There are a bunch of failing shadow map tests.

**Comment by hpinkos** [comment]
I had to go with the `ifdef` solution because I guess you can't read a varying from two different fragment shaders or something.

@bagnell this is ready now

File: Source/Scene/ShadowMapShader.js [hunk 1]
```diff
@@ -17,6 +17,7 @@ define([
     };
 
     ShadowMapShader.createShadowCastVertexShader = function(vs, isPointLight, isTerrain) {
+        vs.defines.push('SHADOW_MAP');
```
Comment (bagnell) [inline Source/Scene/ShadowMapShader.js]: Move this to after `slice` so it doesn't modify the input source.

File: Source/Scene/ShadowMapShader.js [hunk 2]
```diff
@@ -127,6 +128,7 @@ define([
     };
 
     ShadowMapShader.createShadowReceiveVertexShader = function(vs, isTerrain, hasTerrainNormal) {
+        vs.defines.push('SHADOW_MAP');
```
Comment (bagnell) [inline Source/Scene/ShadowMapShader.js]: Same comment.

**Comment by bagnell** [comment]
The rest looks good. Just that minor comment.

File: Source/Scene/ShadowMapShader.js (hunk 1 above)
Comment (hpinkos) [reply Source/Scene/ShadowMapShader.js]: It only works if I modify the input source, because the define needs to be added to the `ShaderSource` that's using the `vertexLogDepth` shader.  Is there a different way to do this?

Comment (bagnell) [reply Source/Scene/ShadowMapShader.js]: The log depth shaders don't use that varying. Only log depth + shadows use it.

**Comment by hpinkos** [comment]
@bagnell I swear it didn't work when I had the define that way originally, but I must have had something else wrong because it seems to be working now.

This is ready
