### PR TITLE
Fix depth fail material in Edge

### LINKED ISSUE #5357: Depth fail does not work in Edge
In Edge, navigate to http://cesiumjs.org/Cesium/Apps/Sandcastle/gallery/Ground%20Clamping.html and selec the last demo in the combo box.  The shared will fail to link.

@bagnell believes this is a bug in Edge where `GL_EXT_frag_depth` is declared in the fragment shader but then not made automatically available in the vertex shader.

### PR DESCRIPTION
**Pull request by bagnell**
Always include frag depth varying even when not supported. Fixes #5357.

### CODE REVIEW

File: Source/Scene/Primitive.js [hunk 1]
```diff
@@ -994,15 +994,11 @@ define([
     function depthClampVS(vertexShaderSource) {
         var modifiedVS = ShaderSource.replaceMain(vertexShaderSource, 'czm_non_depth_clamp_main');
         modifiedVS +=
-            '#ifdef GL_EXT_frag_depth\n' +
```
Comment (pjcozzi) [inline Source/Scene/Primitive.js]: As an explicit optimization, we usually put the `#ifdef` everywhere and do not rely, for example, on the GLSL compiler to optimize out unused code.

Perhaps add a comment here that this is used for frag depth, but it is not in an `#ifdef` to workaround an Edge bug.

Also submit an Edge bug please.

**Comment by mramato** [comment]
I can confirm that this fixes the crash, I'll leave the review and merge up to @pjcozzi 

Thanks @bagnell!

**Comment by bagnell** [comment]
Here is a link to the Edge issue: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12120362/

**Comment by bagnell** [comment]
@pjcozzi This is ready for another look.

**Comment by pjcozzi** [comment]
Very nice, thanks @bagnell @mramato!
