### PR TITLE
Increase max clipping planes using textures

### LINKED ISSUE #6048: Clipping planes broken in IE
See discussion in #6038.

There is an issue with the GLSL compilation in IE that disables clipping plane functionality.

### LINKED ISSUE #6184: Model pick shaders do not use clipping planes
The clipping planes code is added to the model render fragment shader but not the pick fragment shader. In the below example, rotate the camera to be level with the clipping plane and pick where one of the towers would be if it wasn't clipped. It will still be highlighted.

```javascript
// Add a clipping plane, a plane geometry to show the representation of the
// plane, and control the magnitude of the plane distance with the mouse.
// Clipping planes are not currently supported in Internet Explorer.

var viewer = new Cesium.Viewer('cesiumContainer', {
    infoBox: false,
    selectionIndicator: false
});
var scene = viewer.scene;

var clipObjects = ['BIM', 'Point Cloud', 'Instanced', 'Model'];
var viewModel = {
    debugBoundingVolumesEnabled : false,
    edgeStylingEnabled : true,
    exampleTypes : clipObjects,
    currentExampleType : clipObjects[0]
};

var targetY = 0.0;
var planeEntities = [];
var selectedPlane;

// Select plane when mouse down
var downHandler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
downHandler.setInputAction(function(movement) {
    var pickedObject = scene.pick(movement.position);
    if (Cesium.defined(pickedObject) &&
            Cesium.defined(pickedObject.id) &&
            Cesium.defined(pickedObject.id.plane)) {
        selectedPlane = pickedObject.id.plane;
        selectedPlane.material = Cesium.Color.WHITE.withAlpha(0.05);
        selectedPlane.outlineColor = Cesium.Color.WHITE;
        scene.screenSpaceCameraController.enableInputs = false;
    }
}, Cesium.ScreenSpaceEventType.LEFT_DOWN);

// Release plane on mouse up
var upHandler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
upHandler.setInputAction(function() {
    if (Cesium.defined(selectedPlane)) {
        selectedPlane.material = Cesium.Color.WHITE.withAlpha(0.1);
        selectedPlane.outlineColor = Cesium.Color.WHITE;
        selectedPlane = undefined;
    }

    scene.screenSpaceCameraController.enableInputs = true;
}, Cesium.ScreenSpaceEventType.LEFT_UP);

// Update plane on mouse move
var moveHandler = new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas);
moveHandler.setInputAction(function(movement) {
    if (Cesium.defined(selectedPlane)) {
        var deltaY = movement.startPosition.y - movement.endPosition.y;
        targetY += deltaY;
    }
}, Cesium.ScreenSpaceEventType.MOUSE_MOVE);

var scratchPlane = new Cesium.Plane(Cesium.Cartesian3.UNIT_X, 0.0);
function createPlaneUpdateFunction(plane, transform) {
    return function () {
        plane.distance = targetY;
        return Cesium.Plane.transform(plane, transform, scratchPlane);
    };
}

var tileset;
function loadTileset(url) {
    var clippingPlanes = [
        new Cesium.Plane(new Cesium.Cartesian3(0.0, 0.0, -1.0), -100.0)
    ];

    tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
        url : url,
        clippingPlanes : new Cesium.ClippingPlaneCollection({
            planes : clippingPlanes,
            edgeWidth : viewModel.edgeStylingEnabled ? 1.0 : 0.0
        })
    }));

    tileset.debugShowBoundingVolume = viewModel.debugBoundingVolumesEnabled;
    return tileset.readyPromise.then(function() {
        var boundingSphere = tileset.boundingSphere;
        var radius = boundingSphere.radius;

        viewer.zoomTo(tileset, new Cesium.HeadingPitchRange(0.5, -0.2, radius * 4.0));

        for (var i = 0; i < clippingPlanes.length; ++i) {
            var plane = clippingPlanes[i];
            var planeEntity = viewer.entities.add({
                position : boundingSphere.center,
                plane : {
                    dimensions : new Cesium.Cartesian2(radius * 2.5, radius * 2.5),
                    material : Cesium.Color.WHITE.withAlpha(0.1),
                    plane : new Cesium.CallbackProperty(createPlaneUpdateFunction(plane, tileset.modelMatrix), false),
                    outline : true,
                    outlineColor : Cesium.Color.WHITE
                }
            });

            planeEntities.push(planeEntity);
        }
    }).otherwise(function(error) {
        console.log(error);
    });
}

var modelEntityClippingPlanes;
function loadModel(url) {
    var clippingPlanes = [
        new Cesium.Plane(new Cesium.Cartesian3(0.0, 0.0, -1.0), -100.0)
    ];

    modelEntityClippingPlanes = new Cesium.ClippingPlaneCollection({
        planes : clippingPlanes,
        edgeWidth : viewModel.edgeStylingEnabled ? 1.0 : 0.0
    });

    function updateClippingPlanes() {
        return modelEntityClippingPlanes;
    }

    var position = Cesium.Cartesian3.fromDegrees(-123.0744619, 44.0503706, 100.0);
    var heading = Cesium.Math.toRadians(135.0);
    var pitch = 0.0;
    var roll = 0.0;
    var hpr = new Cesium.HeadingPitchRoll(heading, pitch, roll);
    var orientation = Cesium.Transforms.headingPitchRollQuaternion(position, hpr);
    var entity = viewer.entities.add({
        name : url,
        position : position,
        orientation : orientation,
        model : {
            uri : url,
            scale : 8,
            minimumPixelSize : 100.0,
            clippingPlanes : new Cesium.CallbackProperty(updateClippingPlanes, false)
        }
    });

    viewer.trackedEntity = entity;

    for (var i = 0; i < clippingPlanes.length; ++i) {
        var plane = clippingPlanes[i];
        var planeEntity = viewer.entities.add({
            position : position,
            plane : {
                dimensions : new Cesium.Cartesian2(300.0, 300.0),
                material : Cesium.Color.WHITE.withAlpha(0.1),
                plane : new Cesium.CallbackProperty(createPlaneUpdateFunction(plane, Cesium.Matrix4.IDENTITY), false),
                outline : true,
                outlineColor : Cesium.Color.WHITE
            }
        });

        planeEntities.push(planeEntity);
    }
}

// Power Plant design model provided by Bentley Systems
var bimUrl = Cesium.CesiumIon.createResource(1459, { accessToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIzNjUyM2I5Yy01YmRhLTQ0MjktOGI0Zi02MDdmYzBjMmY0MjYiLCJpZCI6NDQsImFzc2V0cyI6WzE0NTldLCJpYXQiOjE0OTkyNjQ3ODF9.SW_rwY-ic0TwQBeiweXNqFyywoxnnUBtcVjeCmDGef4' });
var pointCloudUrl = Cesium.CesiumIon.createResource(1460, { accessToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyMzk2YzJiOS1jZGFmLTRlZmYtYmQ4MS00NTA3NjEwMzViZTkiLCJpZCI6NDQsImFzc2V0cyI6WzE0NjBdLCJpYXQiOjE0OTkyNjQ3NTV9.oWjvN52CRQ-dk3xtvD4e8ZnOHZhoWSpJLlw115mbQJM' });
var instancedUrl = '../../../Specs/Data/Cesium3DTiles/Instanced/InstancedOrientation/';
var modelUrl = '../../SampleData/models/CesiumAir/Cesium_Air.glb';

bimUrl.then(function(resource) {
    return loadTileset(resource);
});

// Track and create the bindings for the view model
var toolbar = document.getElementById('toolbar');
Cesium.knockout.track(viewModel);
Cesium.knockout.applyBindings(viewModel, toolbar);

Cesium.knockout.getObservable(viewModel, 'currentExampleType').subscribe(function(newValue) {
    reset();

    if (newValue === clipObjects[0]) {
        bimUrl.then(function(resource) {
            return loadTileset(resource);
        });
    } else if (newValue === clipObjects[1]) {
        pointCloudUrl.then(function(resource) {
            return loadTileset(resource);
        }).then(function() {
            tileset.clippingPlanes.modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(tileset.boundingSphere.center);
        });
    } else if (newValue === clipObjects[2]) {
        loadTileset(instancedUrl).then(function() {
            tileset.clippingPlanes.modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(tileset.boundingSphere.center);
        });
    } else {
        loadModel(modelUrl);
    }
});

Cesium.knockout.getObservable(viewModel, 'debugBoundingVolumesEnabled').subscribe(function(value) {
    if (Cesium.defined(tileset)) {
        tileset.debugShowBoundingVolume = value;
    }
});

Cesium.knockout.getObservable(viewModel, 'edgeStylingEnabled').subscribe(function(value) {
    var edgeWidth = value ? 1.0 : 0.0;

    if (Cesium.defined(tileset)) {
        tileset.clippingPlanes.edgeWidth = edgeWidth;
    }

    if (Cesium.defined(modelEntityClippingPlanes)) {
        modelEntityClippingPlanes.edgeWidth = edgeWidth;
    }
});

function reset() {
    viewer.entities.removeAll();
    viewer.scene.primitives.removeAll();
    planeEntities = [];
    targetY = 0.0;
}

// Information about the currently selected feature
    var selected = {
        feature: undefined,
        originalColor: new Cesium.Color()
    };

// Information about the currently highlighted feature
    var highlighted = {
        feature: undefined,
        originalColor: new Cesium.Color()
    };

// An entity object which will hold info about the currently selected feature for infobox display
    var selectedEntity = new Cesium.Entity();

// Color a feature on selection and show metadata in the InfoBox.
    var clickHandler = viewer.screenSpaceEventHandler.getInputAction(Cesium.ScreenSpaceEventType.LEFT_CLICK);
    viewer.screenSpaceEventHandler.setInputAction(function onLeftClick(movement) {
        // If a feature was previously selected, undo the highlight
        if (Cesium.defined(selected.feature)) {
            selected.feature.color = selected.originalColor;
            selected.feature = undefined;
        }

        // Pick a new feature
        var pickedFeature = viewer.scene.pick(movement.position);
        if (!Cesium.defined(pickedFeature)) {
            clickHandler(movement);
            return;
        }

        // Select the feature if it's not already selected
        if (selected.feature === pickedFeature) {
            return;
        }
        selected.feature = pickedFeature;

        // Save the selected feature's original color
        if (pickedFeature === highlighted.feature) {
            Cesium.Color.clone(highlighted.originalColor, selected.originalColor);
            highlighted.feature = undefined;
        } else {
            Cesium.Color.clone(pickedFeature.color, selected.originalColor);
        }

        // Highlight newly selected feature
        pickedFeature.color = Cesium.Color.LIME;

        if (!Cesium.defined(pickedFeature.getProperty)) {
            return;
        }

        // Set feature infobox description
        var featureName = pickedFeature.getProperty('name');
        selectedEntity.name = featureName;
        selectedEntity.description = 'Loading <div class="cesium-infoBox-loading"></div>';
        viewer.selectedEntity = selectedEntity;
        selectedEntity.description = '<table class="cesium-infoBox-defaultTable"><tbody>' +
                                     '<tr><th>BIN</th><td>' + pickedFeature.getProperty('BIN') + '</td></tr>' +
                                     '<tr><th>DOITT ID</th><td>' + pickedFeature.getProperty('DOITT_ID') + '</td></tr>' +
                                     '<tr><th>SOURCE ID</th><td>' + pickedFeature.getProperty('SOURCE_ID') + '</td></tr>' +
                                     '</tbody></table>';
    }, Cesium.ScreenSpaceEventType.LEFT_CLICK);


```

### PR DESCRIPTION
**Pull request by likangning93**
Storing the clipping planes in textures leads to a few caveats:
* precision problems with compression to RGBA means plane transformations happen in the shader now instead of on the CPU side
  * so it's a bit more shader math
  * but nice benefit is that the texture doesn't get updated as the view changes - yay!
* attaching a `Texture` gl resource to `ClippingPlaneCollection` means it's no longer super practical to `clone` it onto each model in a 3D Tileset backed by gltf, so now they share the tileset's reference to a single `ClippingPlaneCollection`
* `Texture` also means `ClippingPlaneCollection` now has to be destroyed, but since a `Model` may either have a reference to its own `ClippingPlaneCollection` or a `Cesium3DTileset`'s `ClippingPlaneCollection`, the `destroy` function is a little weird and might need discussion.

There's also a new Sandcastle that I used for debugging. Performance predictably isn't great with all 2048 planes and gets worse as you get closer to the model or use a 3D Tileset. But it works! Even my laptop with Atom Z3700 Series Intel Graphics will gamely throw up a frame or two every couple seconds.

---

Fixes #6184
Fixes #6048

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@likangning93, thanks for the pull request! Maintainers, we have a signed CLA from @likangning93, so you can review this at any time.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by mramato** [comment]
> There's also a new Sandcastle that I used for debugging. Performance predictably isn't great with all 2048 planes and gets worse as you get closer to the model or use a 3D Tileset. But it works! Even my laptop with Atom Z3700 Series Intel Graphics will gamely throw up a frame or two every couple seconds.

This doesn't sound like something we should ship to end users.  We have a `development` directory in Sandcastle gallery for this kind of stuff, I would recommend moving it there.

**Comment by pjcozzi** [comment]
Please bump to me for a final review when ready.  In the meantime, one comment:

> precision problems with compression to RGBA means plane transformations happen in the shader now instead of on the CPU side

We can likely use float textures when available and emulate the 64-bit floating subtraction - which is generally the main cause of jitter - just like we do for vertex positions with RTE rendering.  @bagnell or @lilleyse can point you to example code.

**Comment by likangning93** [comment]
> We can likely use float textures when available and emulate the 64-bit floating subtraction - which is generally the main cause of jitter - just like we do for vertex positions with RTE rendering.

It's kind of nice putting pre-transform planes into the texture though, since we don't have to run CPU-side packing math every frame or do a `gl` call to update the texture due to view changes.

Post-transform planes are also tricky with 3D Tilesets because tiles can have their own matrices - we'd be doing a lot more texture updates in that case, so performance could be really bad.

**Comment by pjcozzi** [comment]
@likangning93 I don't have the bandwidth to work on this right now, but if there is a precision issue please discuss with @bagnell or @lilleyse as I'm confident there is an approach where we could get higher precision and still keep all the work in the shader.

**Comment by pjcozzi** [comment]
* Part of #5765
* Does this fix #6048?
* Does this fix #6184?

File: Specs/Scene/ModelSpec.js [hunk 1]
```diff
@@ -769,6 +769,22 @@ defineSuite([
...
     });
 
+    it('tries to destroy attached ClippingPlaneCollections', function() {
+        return loadModel(boxUrl).then(function(model) {
+            var clippingPlanes = new ClippingPlaneCollection({
+                planes : [
+                    new Plane(Cartesian3.UNIT_X, 0.0)
+                ]
+             });
+             model.clippingPlanes = clippingPlanes;
```
Comment (lilleyse) [inline Specs/Scene/ModelSpec.js]: Fix indentation

File: Specs/Scene/PointCloud3DTileContentSpec.js [hunk 2]
```diff
@@ -920,21 +901,30 @@ defineSuite([
...
+                console.log(rgba);
+            }); // TODO: look at this in Sandcastle
+
             expect(scene).notToRender(color);
 
             tileset.clippingPlanes.unionClippingRegions = false;
 
+            expect(scene).toRenderAndCall(function(rgba) {
+                console.log(rgba);
+            });
```
Comment (lilleyse) [inline Specs/Scene/PointCloud3DTileContentSpec.js]: What's with all the `console.logs` in here?

File: Apps/Sandcastle/gallery/development/Many Clipping Planes.html [hunk 3]
```diff
@@ -0,0 +1,255 @@
+<!DOCTYPE html>
```
Comment (lilleyse) [inline Apps/Sandcastle/gallery/development/Many Clipping Planes.html]: I really like this demo and feel like it could be incorporated into the main clipping planes demo. If that's annoying to do it could be a standalone demo in the main folder.

File: Specs/Scene/PointCloud3DTileContentSpec.js (hunk 2 above)
Comment (likangning93) [reply Specs/Scene/PointCloud3DTileContentSpec.js]: this might be a "whoops" sort of thing...

**Comment by mramato** [comment]
Sorry if this was already discussed, but `ClippingPlaneCollection.isSupported` should be deprecated instead of removed without warning.  (Just have the deprecated version return `true`).

File: Source/Core/ClippingPlaneCollection.js [hunk 4]
```diff
@@ -84,9 +106,39 @@ define([
...
+         */
+        this.owner = undefined;
+
         this._testIntersection = undefined;
         this._unionClippingRegions = undefined;
         this.unionClippingRegions = defaultValue(options.unionClippingRegions, false);
+
+        // Avoid wastefully re-uploading textures when the clipping planes don't change between frames
+        var previousTextureBytes = new ArrayBuffer(ClippingPlaneCollection.TEXTURE_WIDTH * ClippingPlaneCollection.TEXTURE_WIDTH * 4);
+        previousTextureBytes[0] = 1;
```
[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Core/ClippingPlaneCollection.js]: I think the idea was to make sure the texture gets updated with a buffer full of zeros if that's the clipping plane texture produced, but on second thought that's probably impossible so this isn't necessary.

File: Source/Core/ClippingPlaneCollection.js [hunk 5]
```diff
@@ -84,9 +106,39 @@ define([
...
+        // Avoid wasteful re-upload checks within a frame when a ClippingPlaneCollection is shared by many Models in a Cesium3DTileset
+        this._planeTextureDirty = true;
+
+        this._clippingPlanesTexture = undefined;
+
+        // Packed uniform for plane count, denormalization parameters, and clipping union (0 false, 1 true)
+        this._lengthRangeUnion = new Cartesian4();
+
+        // Packed uniform for plane count and denormalization parameters
+        this._lengthRange = new Cartesian3();
```
[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Core/ClippingPlaneCollection.js]: globe and point cloud shaders get regenerated if the `ClippingPlaneCollection` is flipped from union to intersection, while `Model.js` just puts a branch in the shader. I think @pjcozzi mentioned changing `Model.js` to also regenerate shaders on the fly, though. Should that be in a separate PR?

File: Source/Core/ClippingPlaneCollection.js [hunk 6]
```diff
@@ -237,50 +326,149 @@ define([
...
+    var octEncodeScratch = new Cartesian2();
+    var rightShift = 1.0 / 256;
     /**
-     * Applies the transformations to each plane and packs it into an array.
-     * @private
-     *
-     * @param {Matrix4} viewMatrix The 4x4 matrix to transform the plane into eyespace.
-     * @param {Cartesian4[]} [array] The array into which the planes will be packed.
-     * @returns {Cartesian4[]} The array of packed planes.
+     * Encodes a normalized vector into 4 SNORM values in the range [0-255] following the 'oct' encoding.
```
[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Core/ClippingPlaneCollection.js]: It's two 16-bit values spread out over 4 8-bit values. I was following the convention in `AttributeCompression.js`:
```
    /**
     * Encodes a normalized vector into 2 SNORM values in the range of [0-rangeMax] following the 'oct' encoding.
     * ...
     */
    AttributeCompression.octEncodeInRange = function(vector, rangeMax, result) {
        ...
```

File: Source/Core/ClippingPlaneCollection.js [hunk 7]
```diff
@@ -237,50 +326,149 @@ define([
...
+            distanceMin = Math.min(distance, distanceMin);
+            distanceMax = Math.max(distance, distanceMax);
         }
 
-        return array;
+         // Expand distance range a little bit to prevent packing 1s
+         distanceMax += (distanceMax - distanceMin) * CesiumMath.EPSILON3;
+
+         // Normalize all the distances to the range and record them in the typed array.
+         // Check each distance for changes.
```
[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Core/ClippingPlaneCollection.js]: I think in those cases precision issues are more likely to manifest as just not being able to place the plane at centimeter-scale "correctness" as opposed to jitter.

That being said, having read the [vector paper's](http://jcgt.org/published/0003/02/01/) intro on the philosophy behind finite bit-patterns representing finite numbers, it's definitely wasteful to use this "normalizing" method for compressing arbitrary floats :(

Perhaps we should look into packing/unpacking the actual bit pattern instead of a normalization?

[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Core/ClippingPlaneCollection.js]: > Perhaps we should look into packing/unpacking the actual bit pattern instead of a normalization?

Okay I think actually doing that is insane which is why there's so many approximations. What I meant was "maybe we should look into other approximations." Or just use float textures when available, as recommended by @pjcozzi, but that also needs a little more thought about precisions (texture access always returns [0, 1] right?) and I think that adds enough complexity to warrant a separate PR.

File: Source/Scene/Cesium3DTileset.js [hunk 8]
```diff
@@ -802,6 +802,24 @@ define([
                 return this._asset;
             }
         },
+        /**
+         * The {@link ClippingPlaneCollection} used to selectively disable rendering the tileset. Clipping planes are not currently supported in Internet Explorer.
+         *
+         * @type {ClippingPlaneCollection}
+         */
+        clippingPlanes : {
```
[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Scene/Cesium3DTileset.js]: Herm... behavior is weird both here and in `master`, assigning to two tilesets can cause one to be clipped roughly correctly but the other to be clipped incorrectly. In here there's also failures when the tilesets get destroyed.

After a small discussion offline, we're going to use the `owner` field to enforce that `ClippingPlaneCollection`s can't be added to more than one tileset.

I think we can also enforce this in `Model.js` at the public api level too, although there'll kind of be this de-facto exception where `ClippingPlaneCollection`s on tilesets are still referenced by multiple models...

File: Source/Core/ClippingPlaneCollection.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Core/ClippingPlaneCollection.js]: > texture access always returns [0, 1] right?

Apparently not :D
After a small discussion offline, I'll take a look at just enabling floating point textures as the default path, in which case the RGBA code will become a slightly complicated fallback.

File: Source/Core/ClippingPlaneCollection.js [hunk 9]
```diff
@@ -1,29 +1,51 @@
 define([
```
[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Core/ClippingPlaneCollection.js]: It should be fine.

File: Source/Core/ClippingPlaneCollection.js [hunk 10]
```diff
@@ -376,10 +566,45 @@ define([
...
+    /**
+     * The pixel width of a square, power-of-two RGBA UNSIGNED_BYTE texture
+     * with enough pixels to support MAX_CLIPPING_PLANES.
+     *
+     * A plane is a float in [0, 1) packed to RGBA and an Oct32 quantized normal, so 8 bits or 2 pixels in RGBA
+     *
+     * @type {number}
+     * @constant
+     */
+    ClippingPlaneCollection.TEXTURE_WIDTH = CesiumMath.nextPowerOfTwo(Math.ceil(Math.sqrt(ClippingPlaneCollection.MAX_CLIPPING_PLANES * 2)));
```
[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Core/ClippingPlaneCollection.js]: It might still be better to keep it as a POT though. I think I remember something about those being more efficient for GPU memory or something, although I also vaguely remember someone saying something about how that's not necessarily true anymore...

File: Apps/Sandcastle/gallery/development/Many Clipping Planes.html (hunk 3 above)
Comment (likangning93) [reply Apps/Sandcastle/gallery/development/Many Clipping Planes.html]: @mramato recommended moving it to Development since it's more for debugging and performance testing than demonstrating the feature. @pjcozzi also mentioned at one point that we might do actual clipping cylinders, at which point this demo kind of becomes a "wrong" way to achieve the effect.

> I really like this demo

Much appreciated though!

**Comment by likangning93** [comment]
@lilleyse updated, but as a quick heads-up (as discussed offline) I'm going to take a look at how much work it'll be to include a float texture version as primary and move the RGBA version to fallback.

File: CHANGES.md [hunk 11]
```diff
@@ -5,6 +5,7 @@ Change Log
 
 ##### Deprecated :hourglass_flowing_sand:
 * In the `Resource` class, `addQueryParameters` and `addTemplateValues` have been deprecated and will be removed in Cesium 1.45. Please use `setQueryParameters` and `setTemplateValues` instead.
+* `ClippingPlaneCollection` is now supported in Internet Explorer, so `ClippingPlaneCollection.isSupported` has been deprectaed and will be removed in Cesium 1.45.
```
Comment (pjcozzi) [inline CHANGES.md]: Please submit an issue to remind us to do this.

Comment (pjcozzi) [inline CHANGES.md]: Also mention in CHANGES.md that #6184 is fixed.

File: Apps/Sandcastle/gallery/development/Many Clipping Planes.html [hunk 12]
```diff
@@ -207,10 +207,12 @@
...
-        loadTileset(instancedUrl);
-        tileset.readyPromise.then(function () {
-            tileset.clippingPlanes.modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(tileset.boundingSphere.center);
-        });
+        instancedUrl.then(function(resource) {
+            return loadTileset(resource);
+        })
+            .then(function() {
+                tileset.clippingPlanes.modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(tileset.boundingSphere.center);
+            });
```
Comment (lilleyse) [inline Apps/Sandcastle/gallery/development/Many Clipping Planes.html]: Usually in Cesium code we condense this to:

```
        instancedUrl.then(function(resource) {
            return loadTileset(resource);
        }).then(function() {
            tileset.clippingPlanes.modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(tileset.boundingSphere.center);
        });
```

File: Source/Core/ClippingPlaneCollection.js (hunk 10 above)
[the remark this answers is not in the document]
Comment (lilleyse) [reply Source/Core/ClippingPlaneCollection.js]: Bump.

[the remark this answers is not in the document]
Comment (lilleyse) [reply Source/Core/ClippingPlaneCollection.js]: We try to use 1D textures for the 3D Tiles batch table, so there is some precedent there. But it doesn't matter much in the end.

File: Source/Core/ClippingPlaneCollection.js [hunk 13]
```diff
@@ -574,27 +570,62 @@ define([
...
     };
 
     /**
-     * Destroys this ClippingPlaneCollection if it either has no owner or a reference to the owner is passed in.
-     * We only expect an owner to be defined if this collection is shared by one Cesium3DTileset
-     * and a series of Cesium3DTiles with Model content.
+     * Destroys this ClippingPlaneCollectionand its WebGL resources.
      * @private
+     */
+    ClippingPlaneCollection.prototype.destroy = function() {
```
Comment (lilleyse) [inline Source/Core/ClippingPlaneCollection.js]: Round out the doc for this. For example:

```
    /**
     * Destroys the WebGL resources held by this object.  Destroying an object allows for deterministic
     * release of WebGL resources, instead of relying on the garbage collector to destroy this object.
     * <br /><br />
     * Once an object is destroyed, it should not be used; calling any function other than
     * <code>isDestroyed</code> will result in a {@link DeveloperError} exception.  Therefore,
     * assign the return value (<code>undefined</code>) to the object as done in the example.
     *
     * @returns {undefined}
     *
     * @exception {DeveloperError} This object was destroyed, i.e., destroy() was called.
     *
     *
     * @example
     * clippingPlanes = clippingPlanes && clippingPlanes .destroy();
     *
     * @see ClippingPlaneCollection#isDestroyed
     */
```

Comment (lilleyse) [reply Source/Core/ClippingPlaneCollection.js]: Also remove `@private`. See https://github.com/AnalyticalGraphicsInc/cesium/pull/5615#discussion_r166123282

File: Source/Core/ClippingPlaneCollection.js [hunk 14]
```diff
@@ -574,27 +570,62 @@ define([
...
-     * @param {Object} owner An object to check against this ClippingPlaneCollection's owner object
+     * @param {ClippingPlaneCollection} [clippingPlaneCollection] A ClippingPlaneCollection (or undefined) being attached to an object
+     * @param {Object} newOwner An Object that should receive the new ClippingPlaneCollection
+     * @param {String} key The Key for the Object to reference the ClippingPlaneCollection
+     * @private
      */
-    ClippingPlaneCollection.prototype.checkDestroy = function(owner) {
-        if (defined(this.owner) && owner !== this.owner) {
-            return this;
+    ClippingPlaneCollection.setOwnership = function(clippingPlaneCollection, newOwner, key) {
```
Comment (lilleyse) [inline Source/Core/ClippingPlaneCollection.js]: Place `setOwnership` and `isSupported` above the destroy functions, which are usually last.

File: Source/Core/ClippingPlaneCollection.js [hunk 15]
```diff
@@ -574,27 +570,62 @@ define([
...
+        return destroyObject(this);
+    };
+
+    /**
+     * Sets the owner for the input ClippingPlaneCollection if there wasn't another owner.
+     * Destroys the owner's previous ClippingPlaneCollection if setting is successful.
      *
-     * @param {Object} owner An object to check against this ClippingPlaneCollection's owner object
+     * @param {ClippingPlaneCollection} [clippingPlaneCollection] A ClippingPlaneCollection (or undefined) being attached to an object
+     * @param {Object} newOwner An Object that should receive the new ClippingPlaneCollection
```
Comment (lilleyse) [inline Source/Core/ClippingPlaneCollection.js]: Just `owner` is fine.

File: Source/Core/ClippingPlaneCollection.js [hunk 16]
```diff
@@ -574,27 +570,62 @@ define([
...
         }
-
-        if (defined(this._clippingPlanesTexture)) {
-            this._clippingPlanesTexture.destroy();
+        // Destroy the existing ClippingPlaneCollection, if any
+        newOwner[key] = newOwner[key] && newOwner[key].destroy();
+        if (defined(clippingPlaneCollection)) {
+            if (defined(clippingPlaneCollection._owner)) {
+                throw new DeveloperError('ClippingPlaneCollection should only be assigned to one object');
+            }
```
Comment (lilleyse) [inline Source/Core/ClippingPlaneCollection.js]: Wrap the developer error:

```
//>>includeStart('debug', pragmas.debug);
if (defined(clippingPlaneCollection._owner)) {
    throw new DeveloperError('ClippingPlaneCollection should only be assigned to one object');
}
//>>includeEnd('debug');
```

File: CHANGES.md [hunk 17]
```diff
@@ -3,6 +3,9 @@ Change Log
 
 ### 1.43 - 2018-03-01
 
+##### Deprecated :hourglass_flowing_sand:
+* `ClippingPlaneCollection` is now supported in Internet Explorer, so `ClippingPlaneCollection.isSupported` always returns `true`. [#6201](https://github.com/AnalyticalGraphicsInc/cesium/pull/6201)
```
Comment (lilleyse) [inline CHANGES.md]: Mention that the deprecated function will be removed in 1.43.

File: Source/Scene/Model.js [hunk 18]
```diff
@@ -512,11 +512,15 @@ define([
         this.colorBlendAmount = defaultValue(options.colorBlendAmount, 0.5);
 
         /**
-         * The {@link ClippingPlaneCollection} used to selectively disable rendering the model. Clipping planes are not currently supported in Internet Explorer.
+         * The {ClippingPlaneCollection} used to selectively disable rendering the model. Clipping planes are not currently supported in Internet Explorer.
```
Comment (lilleyse) [inline Source/Scene/Model.js]: Remove any occurrences of `Clipping planes are not currently supported in Internet Explorer.`

File: Source/Scene/Model.js [hunk 19]
```diff
@@ -512,11 +512,15 @@ define([
...
+         * @private
          *
          * @type {ClippingPlaneCollection}
          */
-        this.clippingPlanes = options.clippingPlanes;
+        this._clippingPlanes = undefined;
```
Comment (lilleyse) [inline Source/Scene/Model.js]: Documentation is not needed for underscored variables.

File: Source/Scene/Model.js [hunk 20]
```diff
@@ -512,11 +512,15 @@ define([
...
+
+        var clippingPlanes = options.clippingPlanes;
+        ClippingPlaneCollection.setOwnership(clippingPlanes, this, '_clippingPlanes');
```
Comment (lilleyse) [inline Source/Scene/Model.js]: Instead of these two lines, you could just call the setter directly.

`this.clippingPlanes = options.clippingPlanes`

File: Source/Scene/Model.js [hunk 21]
```diff
@@ -997,6 +1001,22 @@ define([
             get : function() {
                 return this._cachedTexturesByteLength;
             }
+        },
+
+        /**
+         * The {ClippingPlaneCollection} used to selectively disable rendering the model.
```
Comment (lilleyse) [inline Source/Scene/Model.js]: `{@link ClippingPlaneCollection}`

File: Source/Scene/Model.js [hunk 22]
```diff
@@ -4369,12 +4389,13 @@ define([
...
 
-        // Check if ClippingPlaneCollection was already destroyed, for instance, by Cesium3DTileset
-        var clippingPlaneCollection = this.clippingPlanes;
-        if (defined(clippingPlaneCollection) && !clippingPlaneCollection.isDestroyed()) {
-            // If not, only destroy if the ClippingPlaneCollection is not owned by a Cesium3DTileset
-            clippingPlaneCollection.checkDestroy(this);
+        // Only destroy the ClippingPlaneCollection if this is the owner - if this model is part of a Cesium3DTileset,
+        // _clippingPlanes references a ClippingPlaneCollection that this model does not own.
+        var clippingPlaneCollection = this._clippingPlanes;
+        if (defined(clippingPlaneCollection) && !clippingPlaneCollection.isDestroyed() && clippingPlaneCollection._owner === this) {
```
Comment (lilleyse) [inline Source/Scene/Model.js]: Perhaps add a getter for `ClippingPlaneCollection.owner` so it doesn't have to access a private var.

**Comment by lilleyse** [comment]
> @lilleyse updated, but as a quick heads-up (as discussed offline) I'm going to take a look at how much work it'll be to include a float texture version as primary and move the RGBA version to fallback.

Sounds good.

File: Source/Core/ClippingPlaneCollection.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (lilleyse) [reply Source/Core/ClippingPlaneCollection.js]: It don't think it hurts if all systems use the vec4 version for now.

Yeah, Model changes will be in another PR.

**Comment by likangning93** [comment]
@lilleyse I added a "naive" float texture implementation.

It's a pretty separate code path with a bunch of modified shaders, but right now both paths use the same uniforms, which might be a little wasteful in the float case but makes for cleaner code (in my opinon). Let me know what you think... things will definitely get messier anyway if we decide that the planes should be double precision or something.

**Comment by likangning93** [comment]
@lilleyse updated!

File: Apps/Sandcastle/gallery/development/Many Clipping Planes.html [hunk 23]
```diff
@@ -0,0 +1,256 @@
...
+        agiHqUrl.then(function(resource) {
+            return loadTileset(resource);
+        });
+    } else if (newValue === clipObjects[2]) {
+        // Point clouds
+        radiusMultiplier = 20.0;
+        pointCloudUrl.then(function(resource) {
+            return loadTileset(resource);
+        })
+            .then(function() {
```
Comment (lilleyse) [inline Apps/Sandcastle/gallery/development/Many Clipping Planes.html]: Update code style here too.

**Comment by likangning93** [comment]
More big changes incoming!

**TL;DR** what's the best way to recompile shaders in `Model.js`?

Couple notes from a chat with @pjcozzi:
* be nice if we can go more "infinite," reallocate texture as needed
  * well, up to context limit, which we can check for in code
* right now we're doing buffer comparisons to determine if we should do a texture update
  * wouldn't it be great if we could have Planes mark themselves as dirty on change?
  * either have to extend `Plane` with a new class (breaking API change) or add functionality to `Plane` specific to `ClippingPlaneCollection`. Which poison to pick?

* not a good idea to rely on early return to break out of long loops - better if we can recompile shaders to the exact plane count. 
  * looping is currently in "builtin" functions, @lilleyse suggests moving to generated code instead for these functions which sounds really good to me
  * big problem is we don't recompile shaders right now in `Model.js` because that's complicated

**Comment by hpinkos** [comment]
@likangning93 @lilleyse are we going to get this in for the release?  This fixes #6184, right?

**Comment by likangning93** [comment]
@hpinkos we wanted to get this done in time, but if there's other major revisions that pop up I can also just open a small separate PR for #6184.

**Comment by hpinkos** [comment]
No problem @likangning93.  We'll just wait until this is ready, no need to open a separate PR

**Comment by likangning93** [comment]
@lilleyse this is ready for another look now!

**Comment by lilleyse** [comment]
Ok, I'll take a look soon.

**Comment by likangning93** [comment]
Back on the topic of packing arbitrary floats to uint8 RGBA, just found out Cesium has code for doing just that in [`BatchTable.js`](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/BatchTable.js#L280).

@pjcozzi @bagnell @lilleyse are there caveats on this? Or did I just neglect to ask?
Either way I feel pretty silly with the complicated dance of normalization and denormalization that's in here right now.

**Comment by pjcozzi** [comment]
@likangning93 I don't recall specifics but there is probably some precision loose, which may not matter in general, and certainty not for a fallback case when `FLOAT` is not supported.

File: Source/Scene/Model.js [hunk 24]
```diff
@@ -3186,6 +3238,12 @@ define([
         var context = frameState.context;
         var scene3DOnly = frameState.scene3DOnly;
 
+        // Retain references to updated source shaders and programs for rebuilding as needed
+        model._sourcePrograms = model.gltf.programs;
+        model._sourceShaders = model.gltf.shaders;
+        model._hasPremultipliedAlpha = hasPremultipliedAlpha(model);
+
+
```
Comment (lilleyse) [inline Source/Scene/Model.js]: Remove extra new line.

File: Source/Scene/Model.js [hunk 25]
```diff
@@ -3729,42 +3787,29 @@ define([
         }
     }
 
-    function modifyShaderForClippingPlanes(shader) {
+    function modifyShaderForClippingPlanes(shader, clippingPlaneCollection, context) {
```
Comment (lilleyse) [inline Source/Scene/Model.js]: `context` isn't used.

File: Source/Scene/Model.js [hunk 26]
```diff
@@ -3729,42 +3787,29 @@ define([
...
-            '        } \n' +
-            '        \n' +
-            '        vec4 clippingPlanesEdgeColor = vec4(1.0); \n' +
-            '        clippingPlanesEdgeColor.rgb = gltf_clippingPlanesEdgeStyle.rgb; \n' +
-            '        float clippingPlanesEdgeWidth = gltf_clippingPlanesEdgeStyle.a; \n' +
-            '        if (clipDistance > 0.0 && clipDistance < clippingPlanesEdgeWidth) \n' +
-            '        { \n' +
-            '            gl_FragColor = clippingPlanesEdgeColor; \n' +
-            '        } \n' +
+        '        gl_FragColor = clippingPlanesEdgeColor;\n' +
```
Comment (lilleyse) [inline Source/Scene/Model.js]: The indentation in the string is off in some parts.

File: Source/Scene/Model.js [hunk 27]
```diff
@@ -4322,6 +4376,84 @@ define([
...
+    function regenerateShaders(model, frameState) {
+        // In regards to _cachedRendererResources:
+        // Fair to assume that this is data that should just never get modified due to clipping planes or model color.
+        // So if clipping planes or model color active:
+        // - delink _rendererResources.*programs and create new dictionaries.
+        // - do NOT destroy any programs - might be used by copies of the model or by might be needed in the future if clipping planes/model color is deactivated
+
+        // If clipping planes/model color inactive:
+        // - destroy _rendererResources.*programs
+        // - relink _rendererResources.*programs to _cachedRendererResources
```
Comment (lilleyse) [inline Source/Scene/Model.js]: If a model has clipping planes and then a minute later has its color set, what happens to the clipping planes-only shader?

File: Source/Scene/Model.js [hunk 28]
```diff
@@ -4380,9 +4517,23 @@ define([
         }
 
         releaseCachedGltf(this);
+        this._sourcePrograms = undefined;
+        this._sourceShaders = undefined;
```
Comment (lilleyse) [inline Source/Scene/Model.js]: Also set `quantizedVertexShaders` to `undefined`?

File: Source/Scene/Model.js [hunk 29]
```diff
@@ -1870,16 +1916,23 @@ define([
...
+    // since this is the version of the program that will be cached.
+    function createProgram(id, model, context, firstBuild) {
+        var programs = model._sourcePrograms;
+        var shaders = model._sourceShaders;
+        var quantizedVertexShaders = model._quantizedVertexShaders;
+
         var program = programs[id];
 
+        var clippingPlaneCollection = model.clippingPlanes;
+        var addClippingPlaneCode = !firstBuild && needsClippingCode(model);
```
Comment (lilleyse) [inline Source/Scene/Model.js]: This needs a similar check for color.

Maybe irrelevant based on the comment above.

File: Source/Scene/getClippingFunction.js [hunk 30]
```diff
@@ -0,0 +1,169 @@
...
+     * @param {ClippingPlaneCollection} clippingPlaneCollection ClippingPlaneCollection with a defined texture.
+     * @returns {String} A string containing glsl functions for retrieving clipping planes.
+     * @private
+     */
+    function getClippingFunction(clippingPlaneCollection) {
+        //>>includeStart('debug', pragmas.debug);
+        Check.typeOf.object('clippingPlaneCollection', clippingPlaneCollection);
+        //>>includeEnd('debug');
+        var unionClippingRegions = clippingPlaneCollection.unionClippingRegions;
+        var clippingPlaneCount = clippingPlaneCollection.length;
```
Comment (lilleyse) [inline Source/Scene/getClippingFunction.js]: `clippingPlaneCount` -> `clippingPlanesLenth`

File: Specs/Core/ClippingPlaneCollectionSpec.js [hunk 31]
```diff
@@ -118,29 +140,344 @@ defineSuite([
...
+        });
+    });
+
+    describe('float texture mode', function() {
+        it('update creates a float texture with no filtering or wrapping to house packed clipping planes', function() {
+            var scene = createScene();
+
+            if (!ClippingPlaneCollection.useFloatTexture(scene._context)) {
+                // Don't fail just because float textures aren't supported
+                return;
```
Comment (lilleyse) [inline Specs/Core/ClippingPlaneCollectionSpec.js]: Make sure to delete the scene before returning. Fix throughout the file.

File: Source/Core/ClippingPlaneCollection.js [hunk 32]
```diff
@@ -57,7 +94,8 @@ define([
          * @type {Boolean}
          * @default true
          */
-        this.enabled = defaultValue(options.enabled, true);
+        this._enabled = false;
+        this.enabled = defaultValue(options.enabled, true); // set using setter
```
[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Core/ClippingPlaneCollection.js]: Ah whoops, I think the doc here was supposed to get taken out b/c it's on a getter/setter now.

File: Source/Core/ClippingPlaneCollection.js [hunk 33]
```diff
@@ -126,35 +183,95 @@ define([
...
+    };
+
     /**
-     * Adds the specified {@link Plane} to the collection to be used to selectively disable rendering
+     * Adds the specified {@link ClippingPlane} to the collection to be used to selectively disable rendering
      * on the outside of each plane. Use {@link ClippingPlaneCollection#unionClippingRegions} to modify
      * how modify the clipping behavior of multiple planes.
      *
-     * @param {Plane} plane The plane to add to the collection.
+     * @param {ClippingPlanePlane} plane The clipping plane plane to add to the collection. Use of Plane objects will be deprecated.
```
[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Core/ClippingPlaneCollection.js]: github feature request: "whoops" response button

File: Source/Core/ClippingPlaneCollection.js [hunk 34]
```diff
@@ -189,9 +306,9 @@ define([
     }
 
     /**
-     * Checks whether this collection contains the given plane.
+     * Checks whether this collection contains a plane equal to the given plane.
      *
-     * @param {Plane} [plane] The plane to check for.
+     * @param {Plane} [plane] The plane or ClippingPlane to check for.
```
[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Core/ClippingPlaneCollection.js]: @ggetz was there a reason for this to be numerical checks instead of reference checks?

I guess it kind of makes sense though if a user is looking to not add a numerically pre-existing clipping plane.

[the remark this answers is not in the document]
Comment (ggetz) [reply Source/Core/ClippingPlaneCollection.js]: Follows what we do for other collections. The numerical check is used in the `remove` function below as well, but other than that, there is not specific need.

File: Source/Scene/Model.js [hunk 35]
```diff
@@ -1896,13 +1949,20 @@ define([
...
+            vs = quantizedVs;
         }
 
-        var premultipliedAlpha = hasPremultipliedAlpha(model);
-        var finalFS = modifyShaderForColor(fs, premultipliedAlpha);
-        if (ClippingPlaneCollection.isSupported()) {
-            finalFS = modifyShaderForClippingPlanes(finalFS);
+        var finalFS = fs;
+        if (needsColorShadingCode(model)) {
+            finalFS = Model._modifyShaderForColor(finalFS, model._hasPremultipliedAlpha);
```
[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Scene/Model.js]: The spec is currently spying on `Model._modifyShaderForColor`, does it work differently?
We're also currently caching the result from `hasPremultipliedApha` because the gltf asset usually gets released.

File: Source/Scene/Model.js (hunk 27 above)
Comment (likangning93) [reply Source/Scene/Model.js]: Ah... I guess this should always be running `destroyIfNotCached`

File: Source/Scene/Batched3DModel3DTileContent.js [hunk 36]
```diff
@@ -501,14 +509,18 @@ define([
...
-        var modelClippingPlanes = this._model.clippingPlanes;
         if (defined(tilesetClippingPlanes)) {
-            tilesetClippingPlanes.clone(modelClippingPlanes);
-            modelClippingPlanes.enabled = tilesetClippingPlanes.enabled && this._tile._isClipped;
-        } else if (defined(modelClippingPlanes) && modelClippingPlanes.enabled) {
-            modelClippingPlanes.enabled = false;
+            // Dereference the clipping planes from the model if they are irrelevant.
+            // Link/Dereference directly to avoid ownership checks.
+            // This will also trigger synchronous shader regeneration to remove or add the clipping plane and color blending code.
+            this._model._clippingPlanes = (tilesetClippingPlanes.enabled && this._tile._isClipped) ? tilesetClippingPlanes : undefined;
```
[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Scene/Batched3DModel3DTileContent.js]: Slight problem, I think a `clippingPlanesDirty` toggle on `model` doesn't allow a way to tell the model that clipping should be disabled because it's irrelevant. That was part of the reasoning behind referencing/dereferencing.

[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Scene/Batched3DModel3DTileContent.js]: Clarified offline, we can have `Model.js` only update its own `_clippingPlaneState` when it owns the clipping plane collection, otherwise it'll rely on b3dm and i3dm to do that, hence the need for the `clippingPlanesDirty` toggle.

[the remark this answers is not in the document]
Comment (likangning93) [reply Source/Scene/Batched3DModel3DTileContent.js]: Another chat offline: consensus is that the method where b3dm and i3dm handle more state stuff for `Model.js` requires more state variables attached to `Model` prototype. Seems like it should be cleaner to have `b3dm` and `i3dm` continue to do their dereference/re-reference thing.

File: Source/Scene/Cesium3DTile.js [hunk 37]
```diff
@@ -1054,10 +1055,27 @@ define([
...
+        var clippingPlanes = tileset.clippingPlanes;
+        var currentClippingPlanesState = 0;
+        if (defined(clippingPlanes) && this._isClipped && clippingPlanes.enabled) {
+            currentClippingPlanesState = clippingPlanes.clippingPlanesState();
+        }
+        // If clippingPlaneState for this tile changed, mark content as clippingPlanesDirty
+        if (currentClippingPlanesState !== this._clippingPlanesState) {
+            this._clippingPlanesState = currentClippingPlanesState;
+            this._content.clippingPlanesDirty = true;
+        }
```
Comment (lilleyse) [inline Source/Scene/Cesium3DTile.js]: Maybe add the clipping planes code to a separate function `updateClippingPlanes`? Just to help keep `update` super simple. Though `this._content.clippingPlanesDirty = false; // reset after content update` will have to stay here.

Comment (lilleyse) [inline Source/Scene/Cesium3DTile.js]: Maybe `clippingPlanesDirty` should be a property of `Cesium3DTile` instead. I think that will be cleaner overall.

File: Source/Scene/Model.js [hunk 38]
```diff
@@ -511,12 +514,20 @@ define([
          */
         this.colorBlendAmount = defaultValue(options.colorBlendAmount, 0.5);
 
+        this.colorShadingEnabled = isColorShadingEnabled(this);
```
Comment (lilleyse) [inline Source/Scene/Model.js]: Change to `this._colorShadingEnabled`

File: Source/Scene/Model.js [hunk 39]
```diff
@@ -511,12 +514,20 @@ define([
...
         /**
-         * The {@link ClippingPlaneCollection} used to selectively disable rendering the model. Clipping planes are not currently supported in Internet Explorer.
+         * Flag for indicating to ModelInstanceCollection that shaders were changed, necessitating updates.
          *
-         * @type {ClippingPlaneCollection}
+         * @type {Boolean}
+         * @private
          */
-        this.clippingPlanes = options.clippingPlanes;
+        this.changedShadersOnLastUpdate = false;
```
Comment (lilleyse) [inline Source/Scene/Model.js]: This flag feels wrong to have. Could `ModelInstanceCollection` instead look to see if model commands are dirty?

File: Source/Scene/Model.js [hunk 40]
```diff
@@ -1870,44 +1914,104 @@ define([
     };
 
     CreateProgramJob.prototype.execute = function() {
-        createProgram(this.id, this.model, this.context);
+        createProgram(this.id, this.model, this.context, true);
```
Comment (lilleyse) [inline Source/Scene/Model.js]: `createProgram` no longer takes the last argument.

File: Source/Scene/Cesium3DTile.js (hunk 37 above)
Comment (likangning93) [reply Source/Scene/Cesium3DTile.js]: *so very much cleaner*

File: Source/Scene/getClippingFunction.js [hunk 41]
```diff
@@ -0,0 +1,168 @@
...
+
+    function clippingFunctionUnion(usingFloatTexture, clippingPlanesLength) {
+        var functionString =
+            'float clip(vec4 fragCoord, sampler2D clippingPlanes, mat4 clippingPlanesMatrix)\n' +
+            '{\n' +
+            '    vec4 position = czm_windowToEyeCoordinates(fragCoord);\n' +
+            '    vec3 clipNormal = vec3(0.0);\n' +
+            '    vec3 clipPosition = vec3(0.0);\n' +
+            '    float clipAmount = 0.0;\n' +
+            '    float pixelWidth = czm_metersPerPixel(position);\n' +
```
Comment (likangning93) [inline Source/Scene/getClippingFunction.js]: @lilleyse dependence on this function causes edge styling to break in orthographic view.
Just setting it to a constant when we switch to orthographic seems fine, but that will need shader recompilation.
Separate PR later?

Comment (likangning93) [reply Source/Scene/getClippingFunction.js]: Discussed offline, should be a quick fix.

**Comment by likangning93** [comment]
@lilleyse ready!

File: Source/Scene/getClippingFunction.js (hunk 41 above)
Comment (lilleyse) [reply Source/Scene/getClippingFunction.js]: Nice fix!

**Comment by lilleyse** [comment]
This looks ready to go to me.

As a side note, the ability to regenerate model shaders now is pretty nice!

**Comment by hpinkos** [comment]
@likangning93 open an issue to remove the deprecated things

**Comment by likangning93** [comment]
Here: https://github.com/AnalyticalGraphicsInc/cesium/issues/6317

File: Source/Core/ClippingPlaneCollection.js [hunk 42]
```diff
@@ -364,22 +633,103 @@ define([
...
     /**
      * Determines if rendering with clipping planes is supported.
      *
-     * @returns {Boolean} <code>true</code> if ClippingPlaneCollections are supported; otherwise, returns <code>false</code>
+     * @returns {Boolean} <code>true</code> if ClippingPlaneCollections are supported
+     * @deprecated
      */
     ClippingPlaneCollection.isSupported = function() {
-        return !FeatureDetection.isInternetExplorer();
+        return true;
```
Comment (hpinkos) [inline Source/Core/ClippingPlaneCollection.js]: This should have a `deprecationWarning`

File: Source/Core/ClippingPlaneCollection.js [hunk 43]
```diff
@@ -126,34 +167,91 @@ define([
...
-            throw new DeveloperError('The maximum number of clipping planes supported is ' + ClippingPlaneCollection.MAX_CLIPPING_PLANES);
+        var newPlaneIndex = this._planes.length;
+        if (plane instanceof ClippingPlane) {
+            var that = this;
+            plane.onChangeCallback = function(index) {
+                setIndexDirty(that, index);
+            };
+            plane.index = newPlaneIndex;
+        } else {
+            this._containsUntrackablePlanes = true;
```
Comment (hpinkos) [inline Source/Core/ClippingPlaneCollection.js]: This should print a `deprecationWarning` too

Comment (likangning93) [reply Source/Core/ClippingPlaneCollection.js]: more use cases for a "whoops" reaction for github...

File: Apps/Sandcastle/gallery/development/Many Clipping Planes.html [hunk 44]
```diff
@@ -0,0 +1,286 @@
...
+function computePlanes() {
+    var stepDegrees = 6.28319 / steps;
+    clippingPlanes = [];
+
+    for (var i = 0; i < steps; i++) {
+        var angle = i * stepDegrees;
+        var dir = new Cesium.Cartesian3();
+        dir.x = 1.0;
+        dir.y = Math.tan(angle);
+        if (angle > 1.57079632679) {
```
Comment (pjcozzi) [inline Apps/Sandcastle/gallery/development/Many Clipping Planes.html]: Here and below, avoid hardcoding values.  There are `PI` constants here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Math.js#L321

File: Apps/Sandcastle/gallery/development/Many Clipping Planes.html (hunk 3 above)
Comment (pjcozzi) [reply Apps/Sandcastle/gallery/development/Many Clipping Planes.html]: I'm not sure about this being in `development`; I just spent awhile looking for it.  At the least, there should be a simple example showing using a lot of clipping planes.

File: Source/Core/Cartesian4.js [hunk 45]
```diff
@@ -817,5 +817,93 @@ define([
...
+    var BIAS = 38.0;
+
+    /**
+     * Packs an arbitrary floating point value to 4 values representable using uint8.
+     *
+     * @param {Number} value A floating point number
+     * @param {Cartesian4} [result] The Cartesian4 that will contain the packed float.
+     * @returns {Cartesian4} A Cartesian4 representing the float packed to values in x, y, z, and w.
+     */
+    Cartesian4.packFloat = function(value, result) {
```
Comment (pjcozzi) [inline Source/Core/Cartesian4.js]: Here and below, add to CHANGES.md or mark these `@private`.

File: Source/Core/ClippingPlane.js [hunk 46]
```diff
@@ -0,0 +1,155 @@
...
+        './defineProperties'
+    ], function(
+        Cartesian3,
+        Check,
+        defined,
+        defineProperties) {
+    'use strict';
+
+    /**
+     * A Plane in Hessian Normal form to be used with ClippingPlaneCollection.
```
Comment (pjcozzi) [inline Source/Core/ClippingPlane.js]: Use `{@link ClippingPlaneCollection}`.

Check out the [Documentation Guide](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/DocumentationGuide) if you need a refresher on best practices.

File: Source/Core/ClippingPlane.js [hunk 47]
```diff
@@ -0,0 +1,155 @@
...
+     * @constructor
+     *
+     * @param {Cartesian3} normal The plane's normal (normalized).
+     * @param {Number} distance The shortest distance from the origin to the plane.  The sign of
+     * <code>distance</code> determines which side of the plane the origin
+     * is on.  If <code>distance</code> is positive, the origin is in the half-space
+     * in the direction of the normal; if negative, the origin is in the half-space
+     * opposite to the normal; if zero, the plane passes through the origin.
+     */
+    function ClippingPlane(normal, distance) {
```
Comment (pjcozzi) [inline Source/Core/ClippingPlane.js]: `normal` and `distance` are required, right?  Shouldn't this throw an exception if they are not defined?

Potentially acceptable but borderline shady if this relies on `UpdateChangedCartesian3`'s constructor function to validation `normal`.

File: Source/Core/ClippingPlane.js [hunk 48]
```diff
@@ -0,0 +1,155 @@
...
+                return this._cartesian3[key];
+            },
+            set : function(value) {
+                //>>includeStart('debug', pragmas.debug);
+                Check.typeOf.number('value', value);
+                //>>includeEnd('debug');
+                if (defined(this._clippingPlane.onChangeCallback) && value !== this._cartesian3[key]) {
+                    this._clippingPlane.onChangeCallback(this._clippingPlane.index);
+                }
+                this._cartesian3[key] = value;
```
Comment (pjcozzi) [inline Source/Core/ClippingPlane.js]: I'm sure everyone is aware that this switches the object instance into dictionary mode with slower member lookups.  Totally fine for the expected use cases here.  I wonder - but do not know for sure - if this also impacts the JIT's ability to optimize other paths using Cartesian3's, e.g., if these Cartesian3's are passed to other functions that were optimized to have a fast path with them - is that rolled back or a slow path is duplicated?  No action required, just curious and I'm sure we will find out if it is an issue...

File: Source/Core/ClippingPlaneCollection.js [hunk 49]
```diff
@@ -1,40 +1,66 @@
...
         './defineProperties',
+        './destroyObject',
         './DeveloperError',
         './FeatureDetection',
         './Intersect',
         './Matrix4',
-        './Plane'
+        './PixelFormat',
+        './Plane',
+        '../Renderer/ContextLimits',
```
Comment (pjcozzi) [inline Source/Core/ClippingPlaneCollection.js]: This file is in `Core`, should it be including all these `Renderer` references?  Or should this file be moved to `Scene` or maybe `Renderer`?

@likangning93 for more on the Cesium stack, see https://cesium.com/blog/2015/05/26/graphics-tech-in-cesium-stack/

File: Source/Core/ClippingPlaneCollection.js [hunk 50]
```diff
@@ -44,20 +70,26 @@ define([
     function ClippingPlaneCollection(options) {
         options = defaultValue(options, defaultValue.EMPTY_OBJECT);
 
+        this._planes = [];
+        this._containsUntrackablePlanes = false;
+
+        // Do partial texture updates if just one plane is dirty.
+        // If many planes are dirty, refresh the entire texture.
+        this._dirtyIndex = -1;
+        this._manyDirtyPlanes = false;
```
Comment (pjcozzi) [inline Source/Core/ClippingPlaneCollection.js]: "many" is vague.  If this means more than one, call it "multiple."

File: Source/Core/ClippingPlaneCollection.js [hunk 51]
```diff
@@ -44,20 +70,26 @@ define([
...
 
-        /**
-         * Determines whether the clipping planes are active.
-         *
-         * @type {Boolean}
-         * @default true
-         */
-        this.enabled = defaultValue(options.enabled, true);
+        this._enabled = false;
+        this.enabled = defaultValue(options.enabled, true); // set using setter
```
Comment (pjcozzi) [inline Source/Core/ClippingPlaneCollection.js]: Why does this need to use the setter?

File: Source/Core/ClippingPlaneCollection.js [hunk 52]
```diff
@@ -84,9 +116,18 @@ define([
...
         this.edgeWidth = defaultValue(options.edgeWidth, 0.0);
 
+        // If this ClippingPlaneCollection has an owner, only its owner should update or destroy it.
+        // This is because in a Cesium3DTileset multiple models may reference the tileset's ClippingPlaneCollection.
+        this._owner = undefined;
+
         this._testIntersection = undefined;
         this._unionClippingRegions = undefined;
-        this.unionClippingRegions = defaultValue(options.unionClippingRegions, false);
+        this.unionClippingRegions = defaultValue(options.unionClippingRegions, false); // set using setter
```
Comment (pjcozzi) [inline Source/Core/ClippingPlaneCollection.js]: I don't know that using the setter here is a good practice - it makes construction harder to follow since it is in multiple places.  _Might_ be better off duplicating that one extra line in the setter here.

File: Source/Core/ClippingPlaneCollection.js [hunk 53]
```diff
@@ -234,53 +346,203 @@ define([
...
-     * @param {Cartesian4[]} [array] The array into which the planes will be packed.
-     * @returns {Cartesian4[]} The array of packed planes.
+     * Encodes a normalized vector into 4 SNORM values in the range [0-255] following the 'oct' encoding.
+     * oct32 precision is higher than the default oct16, hence the additional 2 uint16 values.
      */
-    ClippingPlaneCollection.prototype.transformAndPackPlanes = function(viewMatrix, array) {
-        //>>includeStart('debug', pragmas.debug);
-        Check.typeOf.object('viewMatrix', viewMatrix);
-        //>>includeEnd('debug');
+    function oct32EncodeNormal(vector, result) {
```
Comment (pjcozzi) [inline Source/Core/ClippingPlaneCollection.js]: Is this specific to the clipping plane?  Or should this be a utility function?  Maybe a static function in `AttributeCompression`?

File: Source/Core/ClippingPlaneCollection.js [hunk 54]
```diff
@@ -234,53 +346,203 @@ define([
...
+        // Compute texture requirements for current planes
+        // In RGBA FLOAT, A plane is 4 floats packed to a RGBA.
+        // In RGBA UNSIGNED_BYTE, A plane is a float in [0, 1) packed to RGBA and an Oct32 quantized normal,
+        // so 8 bits or 2 pixels in RGBA.
+        var pixelsNeeded = useFloatTexture ? this.length : this.length * 2;
+        var requiredResolution = computeTextureResolution(pixelsNeeded, textureResolutionScratch);
+
+        if (defined(clippingPlanesTexture)) {
+            var currentPixelCount = clippingPlanesTexture.width * clippingPlanesTexture.height;
+            // Recreate the texture if it isn't big enough or is 4 times larger than it needs to be
```
Comment (pjcozzi) [inline Source/Core/ClippingPlaneCollection.js]: Are you sure 4x is a standard approach?  Seems like a lot.  I forget the details, but for growing/shrinking vectors there is a proof that you want to grow by 2x and then shrink by 1/3 (or something like that, it is not the same as the growth rate) and then it works out well under random add/removes.  Something like that, ha...

File: Source/Core/ClippingPlaneCollection.js [hunk 55]
```diff
@@ -234,53 +346,203 @@ define([
...
+            if (currentPixelCount < pixelsNeeded ||
+                pixelsNeeded < 0.25 * currentPixelCount) {
+                    clippingPlanesTexture.destroy();
+                    clippingPlanesTexture = undefined;
+                }
+        }
+
+        if (!defined(clippingPlanesTexture)) {
```
Comment (pjcozzi) [inline Source/Core/ClippingPlaneCollection.js]: Here and the `if` blocks below, please make sure the test coverage is solid.

File: Source/Core/ClippingPlaneCollection.js [hunk 56]
```diff
@@ -364,22 +633,103 @@ define([
...
+    /**
+     * Returns a Number encapsulating the state for this ClippingPlaneCollection.
+     *
+     * Clipping mode is encoded in the sign of the number, which is just the plane count.
+     * Used for checking if shader regeneration is necessary.
+     *
+     * @returns {Number} A Number that describes the ClippingPlaneCollection's state.
+     * @private
+     */
+    ClippingPlaneCollection.prototype.clippingPlanesState = function() {
```
Comment (pjcozzi) [inline Source/Core/ClippingPlaneCollection.js]: Should this be a getter?

File: Source/Core/ClippingPlaneCollection.js (hunk 42 above)
Comment (pjcozzi) [reply Source/Core/ClippingPlaneCollection.js]: @likangning93 did you add the deprecation warning here?

File: Source/Scene/Cesium3DTileset.js [hunk 57]
```diff
@@ -1930,6 +1947,9 @@ define([
         // Destroy debug labels
         this._tileDebugLabels = this._tileDebugLabels && this._tileDebugLabels.destroy();
 
+        // Destroy clipping plane collection
```
Comment (pjcozzi) [inline Source/Scene/Cesium3DTileset.js]: This comment and `// Destroy debug labels` above are not needed.

Just like `++i; // add one to i` would not be needed.

File: Source/Scene/Model.js [hunk 58]
```diff
@@ -1002,13 +1009,42 @@ define([
...
+        clippingPlanes : {
+            get : function() {
+                return this._clippingPlanes;
+            },
+            set : function(value) {
+                if (value === this._clippingPlanes) {
+                    return;
+                }
+                // Handle destroying, checking of unknown, checking for existing ownership
+                ClippingPlaneCollection.setOwnership(value, this, '_clippingPlanes');
```
Comment (pjcozzi) [inline Source/Scene/Model.js]: Perhaps just `setOwner`?

File: Source/Scene/Model.js [hunk 59]
```diff
@@ -3774,42 +3855,29 @@ define([
...
-            'uniform bool gltf_clippingPlanesUnionRegions; \n' +
-            'uniform vec4 gltf_clippingPlanes[czm_maxClippingPlanes]; \n' +
+            'uniform sampler2D gltf_clippingPlanes; \n' +
             'uniform vec4 gltf_clippingPlanesEdgeStyle; \n' +
+            'uniform mat4 gltf_clippingPlanesMatrix; \n' +
             'void main() \n' +
             '{ \n' +
             '    gltf_clip_main(); \n' +
-            '    if (gltf_clippingPlanesLength > 0) \n' +
+            '    float clipDistance = clip(gl_FragCoord, gltf_clippingPlanes, gltf_clippingPlanesMatrix);' +
```
Comment (pjcozzi) [inline Source/Scene/Model.js]: Is this specific to glTF or is there a **reasonable** way to encapsulate this so the same GLSL code/function is used for the globe shadre as well?

File: Source/Scene/getClippingFunction.js [hunk 60]
```diff
@@ -0,0 +1,168 @@
...
+        '../Renderer/PixelDatatype',
+        './getUnpackFloatFunction'
+    ], function(
+        Check,
+        PixelDatatype,
+        getUnpackFloatFunction) {
+    'use strict';
+
+    /**
+     * Gets the glsl functions needed to retrieve clipping planes from a ClippingPlaneCollection's texture.
```
Comment (pjcozzi) [inline Source/Scene/getClippingFunction.js]: "GLSL"

Here, below, and throughout.

File: Source/Scene/getUnpackFloatFunction.js [hunk 61]
```diff
@@ -0,0 +1,42 @@
...
+     * Gets a glsl function that takes a vec4 representing a float packed to Uint8 RGBA and returns the unpacked float.
+     *
+     * @param {String} [functionName='unpackFloat'] An optional name for the glsl function.
+     * @returns {String} A string containing a glsl function that takes a vec4 and returns a float.
+     * @private
+     * @see Cartesian4#packFloat
+     */
+    function getUnpackFloatFunction(functionName) {
+        if (!defined(functionName)) {
+            functionName = 'unpackFloat';
```
Comment (pjcozzi) [inline Source/Scene/getUnpackFloatFunction.js]: Why does this ever need another name and why can't it just be a built-in `czm_` GLSL function?

File: Source/Scene/getClippingFunction.js [hunk 62]
```diff
@@ -0,0 +1,168 @@
+define([
```
Comment (pjcozzi) [inline Source/Scene/getClippingFunction.js]: Does this belong in `Renderer` or `Scene`?  Probably wherever the plane collection lives.

File: Source/Shaders/Builtin/Functions/transformPlane.glsl [hunk 63]
```diff
@@ -0,0 +1,8 @@
+vec4 czm_transformPlane(mat4 transform, vec4 clippingPlane) {
```
Comment (pjcozzi) [inline Source/Shaders/Builtin/Functions/transformPlane.glsl]: Should the parameter order be (plane, transform)?  Whatever is consistent.

**Comment by pjcozzi** [comment]
Also a disclaimer that I did not look at the tests.

File: Source/Core/ClippingPlaneCollection.js (hunk 53 above)
Comment (likangning93) [reply Source/Core/ClippingPlaneCollection.js]: That makes a lot of sense, but it seems like we'd also want to rename a bunch of stuff in `AttributeCompression` to indicate 16-bit-vec2, which seems like it could be a pretty big breaking change.

@lilleyse what do you think? I guess we could also deprecate the current functions over time?

File: Source/Core/ClippingPlaneCollection.js (hunk 54 above)
Comment (likangning93) [reply Source/Core/ClippingPlaneCollection.js]: I think we're more worried about increasing the amortization of cost (reducing # of expensive synchronous GL calls) than minimizing the amount of GPU memory use. If the number of clipping planes is high enough that users start to worry about the size of the clipping plane texture instead of the size of their assets, shading performance will already be pretty much unusable.

I also suspect "optimal" parameters for downsizing res-arrays assume `pop` operations, while we're allowing `delete` which makes removal "unconditionally expensive." We're even allowing users to add/remove as many `ClippingPlane` objects as they want before res-array logic takes place, so taken altogether I don't think optimizing the growth/shrink rate will lead to tangible performance improvements.

@lilleyse any thoughts?

Comment (likangning93) [reply Source/Core/ClippingPlaneCollection.js]: I'll include a note though, comparison to standard res-array is still super interesting.

File: Source/Scene/Model.js (hunk 59 above)
Comment (likangning93) [reply Source/Scene/Model.js]: We could re-use this in `PointCloud3DTileContent`, but the logic is baked into `GlobeFS.glsl` and enabled/disabled using injected defines.

I'll go ahead and move it out, it'll be handy in case at some point we want to make all things clippable.
