### PR TITLE
Billboard transparency

### LINKED ISSUE #2130: Transparent billboards/points not working as expected.
From the mailing list: https://groups.google.com/d/msg/cesium-dev/_RSvkl1M9d8/fDV7_ZgBBXkJ
1. Pase this gist into Sandcastle: https://gist.github.com/rlittlefield/e7ee65ccf3f103fcc78d
2. Select "add polyline to old collection"
3. Select "add polyline to new collection"

Orient the camera so that the billboard is visual in front of both lines, you'll see a screenshot similar to the below.  I would expect both lines to behave like the line on the left.

Here's a screenshot
image

### PR DESCRIPTION
**Pull request by bagnell**
Fixes #2130.

### CODE REVIEW

**Comment by emackey** [comment]
Of course, it should be noted that this hurts performance for apps that use large numbers of billboards and points, because they are now drawn 2-pass instead of single-pass.  But the visual improvement may be worth the cost.

**Comment by mramato** [comment]
> Of course, it should be noted that this hurts performance for apps that use large numbers of billboards and points, because they are now drawn 2-pass instead of single-pass. But the visual improvement may be worth the cost.

Feedback has shown that it is absolutely worth the cost.  Visual quality improvements is something that is asked on the forum on a constant basis.

File: Source/Scene/BillboardCollection.js [hunk 1]
```diff
@@ -1502,21 +1519,22 @@ define([
             vaLength = va.length;
 
             colorList.length = vaLength;
-            for (j = 0; j < vaLength; ++j) {
+            for (j = 0; j < vaLength * 2; ++j) {
```
Comment (pjcozzi) [inline Source/Scene/BillboardCollection.js]: Minor, but extract `* 2` from the loop.

File: Source/Scene/BillboardCollection.js [hunk 2]
```diff
@@ -1482,11 +1483,27 @@ define([
                     vs.defines.push('DISTANCE_DISPLAY_CONDITION');
                 }
 
+                fs = new ShaderSource({
```
Comment (pjcozzi) [inline Source/Scene/BillboardCollection.js]: Here and in the point cloud, shouldn't the render state be different for each pass?  Opaque writes depth; translucent does not.

File: Source/Shaders/BillboardCollectionFS.glsl [hunk 3]
```diff
@@ -15,13 +15,28 @@ void main()
 #else
     vec4 vertexColor = v_color;
 #endif
-    
+
     vec4 color = texture2D(u_atlas, v_textureCoordinates) * vertexColor;
-    if (color.a == 0.0)
+
+#ifdef RENDER_FOR_PICK
```
Comment (pjcozzi) [inline Source/Shaders/BillboardCollectionFS.glsl]: Can you add a comment here and to the point shader that explains this?  For example: fully transparent parts are not pickable, and the billboard/point is rendered twice: the opaque pass discards translucent fragments, and the translucent pass discards opaque ones.

File: Source/Scene/PointPrimitiveCollection.js [hunk 4]
```diff
@@ -892,21 +909,22 @@ define([
...
-                    command = colorList[j] = new DrawCommand({
-                        primitiveType : PrimitiveType.POINTS,
-                        pass : Pass.OPAQUE,
-                        owner : this
-                    });
+                    command = colorList[j] = new DrawCommand();
                 }
 
+                command.primitiveType = PrimitiveType.POINTS;
+                command.pass = (j % 2 === 0) ? Pass.OPAQUE : Pass.TRANSLUCENT;
```
Comment (pjcozzi) [inline Source/Scene/PointPrimitiveCollection.js]: Let's make a public enum with the following properties:
* `OPAQUE`
* `TRANSLUCENT`
* `OPAQUE_AND_TRANSLUCENT`

Billboard, label, and point collections can expose this property (get/set ideally) and default to `OPAQUE_AND_TRANSLUCENT`.  Make sure the reference doc clearly defines the performance vs. visual quality tradeoffs.

**Comment by pjcozzi** [comment]
Add unit tests.  Checking the number of commands returned by `update` and their `Pass` would be good.

**Comment by pjcozzi** [comment]
Just those comments.

**Comment by bagnell** [comment]
@pjcozzi This is ready for another look.

File: Source/Scene/BillboardCollection.js [hunk 5]
```diff
@@ -133,6 +135,9 @@ define([
      * @param {Matrix4} [options.modelMatrix=Matrix4.IDENTITY] The 4x4 transformation matrix that transforms each billboard from model to world coordinates.
      * @param {Boolean} [options.debugShowBoundingVolume=false] For debugging only. Determines if this primitive's commands' bounding spheres are shown.
      * @param {Scene} [options.scene] Must be passed in for billboards that use the height reference property or will be depth tested against the globe.
+     * @param {BillboardRenderTechnique} [options.renderTechnique=BillboardRenderTechnique.OPAQUE_AND_TRANSLUCENT] The billboard rendering technique. The default
```
Comment (pjcozzi) [inline Source/Scene/BillboardCollection.js]: Should this be exposed on `LabelCollection` as well?

I don't think users would use the opaque version, but they would likely use the translucent one for a performance boost.

File: Source/Scene/BillboardRenderTechnique.js [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+], function(
+    freezeObject) {
+    'use strict';
+
+    /**
+     * Determines how billboards and points are rendered.
+     *
+     * @exports BillboardRenderTechnique
+     */
+    var BillboardRenderTechnique = {
```
Comment (pjcozzi) [inline Source/Scene/BillboardRenderTechnique.js]: Given that this applies to points and labels as well, I don't think it should have `Billboard` in the name.  I am also hesitant about having `technique` in the name since in glTF and computer graphics, this isn't really a technique in the material sense.

Perhaps throughout, this is better named `BlendOption` (too confusing with blend mode? probably not at this level of the API), `ImageBlendOption`, `RenderPasses` (again, too similar to the renderer?), or `CompositeMode`?  Ignore the implementation and think about what would sound reasonable to the end user.

File: CHANGES.md [hunk 7]
```diff
@@ -34,6 +34,7 @@ Change Log
 * `TerrainProvider` now optionally exposes an `availability` property that can be used to query the terrain level that is available at a location or in a rectangle.  Currently only `CesiumTerrainProvider` exposes this property.
 * Added `sampleTerrainMostDetailed` to sample the height of an array of positions using the best available terrain data at each point.  This requires a `TerrainProvider` with the `availability` property.
 * Added 2D and Columbus View support for models using the RTC extension or whose vertices are in WGS84 coordinates. [#4922](https://github.com/AnalyticalGraphicsInc/cesium/pull/4922)
+* Transparent parts of billboards, labels, and points no longer overwrite parts of the scene behind them. [#4886](https://github.com/AnalyticalGraphicsInc/cesium/pull/4886)
```
Comment (pjcozzi) [inline CHANGES.md]: Update this.

File: Source/Scene/BillboardCollection.js [hunk 8]
```diff
@@ -268,6 +275,16 @@ define([
          */
         this.debugShowBoundingVolume = defaultValue(options.debugShowBoundingVolume, false);
 
+        /**
+         * The billboard rendering technique. The default is used for rendering both opaque and translucent billboards.
+         * However, if either all of the billboards are completely opaque or all are completely translucent,
+         * setting the technique to BillboardRenderTechnique.OPAQUE or BillboardRenderTechnique.TRANSLUCENT can improve performance by 2x.
```
Comment (pjcozzi) [inline Source/Scene/BillboardCollection.js]: Here and throughout, perhaps "up to 2x"

**Comment by pjcozzi** [comment]
Just those comments.

File: Source/Scene/BillboardCollection.js (hunk 5 above)
Comment (bagnell) [inline Source/Scene/BillboardCollection.js]: I was thinking that they would always be both, but that isn't true anymore with the label backgrounds. I'll add it.

**Comment by bagnell** [comment]
@pjcozzi This is ready.

**Comment by pjcozzi** [comment]
Amazing.

**Comment by Petter-li** [comment]
I still have the problem. billboards img set a png, the transparency part is disappear; 
version:"cesium": "^1.55.0";
can u guys told me how to fix it. Thanks.

**Comment by BoJIbFbI4** [comment]
hi, same for 1.71. I'm wanna change alpha for pins that not selected for a little bit, but no matter to pin's alpha, if polygon has alpha - pins will be faded
polygon with alpha:
image
image
polygon w/o alpha:
image
image

**Comment by BoJIbFbI4** [comment]
@OmarShehata, hi. Thnx for the quick response! For me build the 99% same behavior example will take unforgivable amount of time. Maybe you know that 'fixed' issue, or can give me some advice?
