### PR TITLE
8321/polyline crash

### LINKED ISSUE #8321: PolylineCollection update instanceIndex is out of range
Browser: Chrome
Operating System: MacOS
Cesium version: 1.5.3

Hi, we have an app where we create and destroy a bunch of Polyline's. Basically the user cycles through different polylines, and every time they select a new one we delete the ones they were previously looking at and create the ones they're looking at now using. 

The polylines also have a `CallbackProperty` on the `positions` property that updates the positions every frame.

We get an error from Cesium originating on this line:

https://github.com/AnalyticalGraphicsInc/cesium/blob/d26ccfea38dcf4623cf5da3faca141913c64cfe1/Source/Scene/PolylineCollection.js#L471

Quite reliably when we delete a set of polylines and then immediately render frames. If we remove the `CallbackProperty` the error does not occur.

Are we hitting some race condition bug where callback properties are setting a dirty flag on polylines that already have been deleted?

We're creating the polylines with `viewer.entities.add` and destroying them with `viewer.entities.remove`.

Screen Shot 2019-10-25 at 4 53 17 PM

### PR DESCRIPTION
**Pull request by Samulus**
Fixes #8321 

This crash is caused by `polyLinesToUpdate` becoming out of sync with `polyLines`.  If the position of a polyLine is marked as dirty (i.e `.position = ....` is invoked) and the polyline is marked for removal, the polyLine will remain in the polyLinesToUpdate array, but not the main polyLines array. The arrays become out of sync and a failure occurs when we try to update a deleted polyLine

Tested on Linux / Nvidia

Test case here: http://localhost:8080/Apps/Sandcastle/index.html#c=lZJPb5wwEMW/yohLWGllkuyty64akUukSKnUP5eSgwOzWyvGRmPDilb73TtgWEKiHsrJ9rx583s2rSRoFZ6QYAcGT5ChU00lfgxn8VUxbDNrvFQG6Wq1zU1uWu4qrNZYeGXNsvOL1Z1mbXapx31TGCJcgQZFTapSXrXohCzLeLYK9kkCGaH0CPVo5oDw2GhJusuNQ/9gPFIrdVwMumnmGm6ug8WhMYFtKYhX8Cc3wF8fYXLnADPCQDSK+q+2TvXn7tOUMJPkeSXNRhzIVvd4JER3RyS7+Oc1M6zhdg2b51UwOQeifsnBvtdlCDa6gj14NDNTM9SnfEz2Nu0l1ZwjIIYcYnbd/TfsdqSd73AkvmNAAgleVXzBzts6QCpzBGlKfpnKthjkDPuNZbbx/2ItNEq6BFqmnRgG3fwgYUA8pVyQDqjn3ETrKHW+07gPxc+qqi15aEjHQiQeq1rzJJe8NMUrelE413emydSUlqoFVe7y6N0vn0fMLJ3jyqHR+qv6jXm0TxPWL9q0lSVfyVOLpGXXS37d7B/DoRAiTXj7sctbq18kvXH8Cw

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @Samulus!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/8321/polyline_crash/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

File: Source/Scene/PolylineCollection.js [hunk 1]
```diff
@@ -1049,19 +1049,29 @@ import SceneMode from './SceneMode.js';
     function removePolylines(collection) {
         if (collection._polylinesRemoved) {
             collection._polylinesRemoved = false;
+            var definedPolylines = [];
+            var polyIndex=0;
```
Comment (lilleyse) [inline Source/Scene/PolylineCollection.js]: Style:
```suggestion
            var polyIndex = 0;
```

File: Source/Scene/PolylineCollection.js [hunk 2]
```diff
@@ -1049,19 +1049,29 @@ import SceneMode from './SceneMode.js';
...
+            var polyline;
+            var i;
 
-            var polylines = [];
-
-            var length = collection._polylines.length;
-            for ( var i = 0, j = 0; i < length; ++i) {
-                var polyline = collection._polylines[i];
+            for (i=0; i < collection._polylines.length; ++i) {
```
Comment (lilleyse) [inline Source/Scene/PolylineCollection.js]:
```suggestion
            for (i = 0; i < collection._polylines.length; ++i) {
```

File: Source/Scene/PolylineCollection.js [hunk 3]
```diff
@@ -1049,19 +1049,29 @@ import SceneMode from './SceneMode.js';
...
                 if (defined(polyline)) {
-                    polyline._index = j++;
-                    polylines.push(polyline);
+                    polyline._index = polyIndex++;
+                    definedPolylines.push(polyline);
+                }
+            }
+
+            var definedPolylinesToUpdate = [];
+            for (i=0; i < collection._polylinesToUpdate.length; ++i) {
```
Comment (lilleyse) [inline Source/Scene/PolylineCollection.js]:
```suggestion
            for (i = 0; i < collection._polylinesToUpdate.length; ++i) {
```

File: Source/Scene/PolylineCollection.js [hunk 4]
```diff
@@ -1049,19 +1049,29 @@ import SceneMode from './SceneMode.js';
...
         if (collection._polylinesRemoved) {
             collection._polylinesRemoved = false;
+            var definedPolylines = [];
+            var polyIndex=0;
+            var polyline;
+            var i;
 
-            var polylines = [];
-
-            var length = collection._polylines.length;
```
Comment (lilleyse) [inline Source/Scene/PolylineCollection.js]: Style / performance: cesium code intentionally stores the length in a separate variable so that iteration is faster. Probably less important now that JS engines are much faster than in 2011 but it's a convention that has remained in the code.

File: Source/Scene/PolylineCollection.js [hunk 5]
```diff
@@ -1049,19 +1049,29 @@ import SceneMode from './SceneMode.js';
...
-                    polylines.push(polyline);
+                    polyline._index = polyIndex++;
+                    definedPolylines.push(polyline);
+                }
+            }
+
+            var definedPolylinesToUpdate = [];
+            for (i=0; i < collection._polylinesToUpdate.length; ++i) {
+                polyline = collection._polylines[i];
+                if (defined(polyline) && defined(polyline._polylineCollection)) {
```
Comment (lilleyse) [inline Source/Scene/PolylineCollection.js]: I like that `polylinesToUpdate` filtering has moved here instead, but I wonder if it can be taken further.

This line in `remove` still kinda bugs me:
 `this._polylines[polyline._index] = undefined; // Removed later`.

Would it be cleaner to delete that line and filter `polylines` the same why `polylinesToUpdate` is filtered here, i.e. by checking that `polyline._polylineCollection` is defined? Or even better, add a private getter `isDestroyed` to `Polyline` that returns true if `polyline._polylineCollection` is undefined and use the getter instead.

Anywhere that checks if a polyline is defined would instead check `polyline.isDestroyed()`. `removePolylines`, `releaseShaders` and `destroyPolylines` would need to be updated.

**Comment by lilleyse** [comment]
Also, is it possible to find a reproducible test case that could be unit tested?

**Comment by mramato** [comment]
Awesome work @Samulus.

@tinco can you confirm that this branch fixes your issue?

**Comment by tinco** [comment]
Epic, I'll try swapping over our production to this release, hopefully there's nothing incompatible going on in master besides this fix :) If it's fixed I should see no more occurrences from today on, I'll know by wednesday next week for sure.

**Comment by tinco** [comment]
Hm I can't get master to work, something changed with `esm`, I get errors about not being able to resolve `fs` and `module`, which makes sense since we're trying to run this in the browser, but I'm not sure how to fix this. Is this no longer how you use webpack with cesium?: https://gist.github.com/tinco/8f423938bb9dd4fc8edc1fa86ab017b3

**Comment by mramato** [comment]
@tinco not sure about your setup, but see https://github.com/AnalyticalGraphicsInc/cesium-webpack-example/blob/master/webpack.config.js for a known working configuration with ES6 versions of Cesium.  (That whole repository is a standalone example with both debug and release configs, I linked to the debug one I think)

**Comment by tinco** [comment]
Just tested master on that repo @mramato, it fails there as well, so I guess something really is broken on master for webpack!

**Comment by mramato** [comment]
@tinco I was unable to reproduce.  To avoid derailing this issue, can you write up an issue at https://github.com/AnalyticalGraphicsInc/cesium-webpack-example/issues with details.  Thanks!

**Comment by Samulus** [comment]
> 
> 
> Also, is it possible to find a reproducible test case that could be unit tested?
@lilleyse I think that the `PolylineCollectionSpec.prototype.update` function combined with `setInterval` is critical to replicating this error. I tried a bunch of different permutations of mutating the collection without calling `.update` inbetween and couldn't reproduce the same error we see in the Sandcastle demo. Is there a (sane) way of mocking out a `frameState` in a Jasmine test?

File: Source/Scene/Polyline.js [hunk 6]
```diff
@@ -285,6 +285,19 @@ import Material from './Material.js';
             }
         },
 
+        /**
+         * Gets the destruction status of this polyline
+         * @memberof Polyline.prototype
+         * @type {Boolean}
+         * @default undefined
```
Comment (lilleyse) [inline Source/Scene/Polyline.js]:
```suggestion
         * @default false
```

File: Specs/Scene/PolylineCollectionSpec.js [hunk 7]
```diff
@@ -316,31 +316,32 @@ describe('Scene/PolylineCollection', function() {
...
         var firstPolyline = polylines.add();
         var secondPolyline = polylines.add();
 
         firstPolyline.width = 4;
         secondPolyline.width = 5;
 
         expect(polylines._polylinesToUpdate.length).toEqual(2);
-
         polylines.remove(secondPolyline);
+        polylines.update(scene._frameState);
```
Comment (lilleyse) [inline Specs/Scene/PolylineCollectionSpec.js]:
```suggestion
        polylines.update(scene.frameState);
```

File: Specs/Scene/PolylineCollectionSpec.js [hunk 8]
```diff
@@ -316,31 +316,32 @@ describe('Scene/PolylineCollection', function() {
...
 
         firstPolyline.width = 4;
         secondPolyline.width = 5;
-        secondPolyline.width = 7;
+        secondPolyline.width = 7; // Making the polyline dirty twice shouldn't affect the length of `_polylinesToUpdate`
 
         expect(polylines._polylinesToUpdate.length).toEqual(2);
 
         polylines.remove(secondPolyline);
+        polylines.update(scene._frameState);
```
Comment (lilleyse) [inline Specs/Scene/PolylineCollectionSpec.js]:
```suggestion
        polylines.update(scene.frameState);
```

File: Source/Scene/PolylineCollection.js [hunk 9]
```diff
@@ -1049,27 +1042,31 @@ import SceneMode from './SceneMode.js';
...
+            var polyIndex = 0;
+            var polyline;
 
             var length = collection._polylines.length;
-            for ( var i = 0, j = 0; i < length; ++i) {
-                var polyline = collection._polylines[i];
-                if (defined(polyline)) {
-                    polyline._index = j++;
-                    polylines.push(polyline);
+            var definedPolylinesToUpdate = [];
```
Comment (lilleyse) [inline Source/Scene/PolylineCollection.js]: Small nitpick, but you can you move `var definedPolylinesToUpdate = [];` so it's placed after `var definedPolylines = [];`?

**Comment by lilleyse** [comment]
Oh, and please update `CHANGES.md`!

**Comment by Samulus** [comment]
@lilleyse All comments addressed 👍

**Comment by lilleyse** [comment]
Looks great, thanks @Samulus!
