### PR TITLE
Fix viewer.flyTo ignoring and resetting minimumZoomDistance

### LINKED ISSUE #5573: viewer.flyTo on billboards breaks zoom limits
I feel like this may have been mentioned before, but the `flyTo` method doesn't respect the zoom limits. For my case particularly it is zooming in way closer than the desired max zoom for billboards, but I'm guessing it isn't limited to that.

In addition, if you fly to a billboard, it seems to break the max zoom, because after that, you can zoom to any zoom level in both 2D and 3D, and it won't restrict you. It doesn't break the min zoom, so you can't zoom out infinitely, but you can seemingly zoom in infinitely

### PR DESCRIPTION
**Pull request by burn123**
This fixes #5573.
I might have messed something up by doing this, but here goes my best shot!

For some reason, the `screenSpaceCameraController.minimumZoomDistance` was being set to the radius of the bounding sphere, which happened to be always zero, when zooming to an entity or billboard. As the `maximumZoomDistance` is never set in this way, and [this was the commit message](https://github.com/AnalyticalGraphicsInc/cesium/commit/245af6784a38350cf0fa19d8a21956465dfc731b) when that block of code was added. So I figured that wasn't particularly necessary anymore.

If nothing else, you could probably keep the tests!

### CODE REVIEW

**Comment by hpinkos** [comment]
Thanks @burn123!  @ggetz can you review?

File: Source/Scene/Camera.js [hunk 1]
```diff
@@ -2853,18 +2853,24 @@ define([
...
 
+        var DEFAULT_ZOOM = 100.0;
+        var MINIMUM_ZOOM = camera._scene.screenSpaceCameraController.minimumZoomDistance;
+        var MAXIMUM_ZOOM = camera._scene.screenSpaceCameraController.maximumZoomDistance;
         var range = offset.range;
         if (!defined(range) || range === 0.0) {
             var radius = boundingSphere.radius;
-            if (radius === 0.0) {
+            // If the minimumZoomDistance hasn't been set yet, it is equal to 1,
+            if (radius < MINIMUM_ZOOM && MINIMUM_ZOOM > 1) {
```
Comment (ggetz) [inline Source/Scene/Camera.js]: I'm a little confused why we can't default to the minimum zoom always.

Also see `CesiumMath.clamp`, that might simplify this if/else block a little.

Comment (burn123) [inline Source/Scene/Camera.js]: I was taking the approach that if the radius is 0, it would go to the default zoom unless the minimum zoom had been set already. If you zoom all the way to 1, it doesn't look very good, just a bunch of grey, because it is too close to the surface.

Comment (ggetz) [inline Source/Scene/Camera.js]: Ok I see. However checking if it's < 1 doesn't guarantee the minimumZoom hasn't been set. Would it make sense to set minimumZoom to default to a higher value? @hpinkos

**Comment by burn123** [comment]
@ggetz See if this is what you had in mind. I actually think the minimumZoom problem was fixed by using `clamp`

**Comment by ggetz** [comment]
Thanks @burn123, the code looks good to me, but there is one failing unit test now.

**Comment by burn123** [comment]
@ggetz I think the only failing test is something with the 3D Tile Spec, and it says "Async callback was not invoked within timeout", which I don't believe is related to this. I think I was getting that error on master as well.

**Comment by ggetz** [comment]
I opened #5671 for the test failure.

Other than that, this looks good to me. @hpinkos is this good to go?

**Comment by burn123** [comment]
@hpinkos Did you have a chance to look at this yet?

**Comment by hpinkos** [comment]
I'll take a look at this first thing tomorrow

**Comment by burn123** [comment]
@hpinkos Do you think it would be possible to get this in by the next release? Our application is built on Cesium, but there is a good chance we will stay on Cesium 1.36 for a while, so it would be very useful to have this fixed. But I know you guys are busy, so I understand if not!

**Comment by hpinkos** [comment]
Yes, thanks for the reminder.  I'll look at this now

File: Source/Scene/Camera.js [hunk 2]
```diff
@@ -2853,23 +2853,25 @@ define([
...
     }
 
-    var MINIMUM_ZOOM = 100.0;
-
     function adjustBoundingSphereOffset(camera, boundingSphere, offset) {
         if (!defined(offset)) {
             offset = HeadingPitchRange.clone(Camera.DEFAULT_OFFSET);
         }
 
+        var defaultZoom = 100.0;
```
Comment (hpinkos) [inline Source/Scene/Camera.js]: Move this back outside of the function where it was before

File: Source/Scene/Camera.js [hunk 3]
```diff
@@ -2853,23 +2853,25 @@ define([
...
+        var minimumZoom = camera._scene.screenSpaceCameraController.minimumZoomDistance;
+        var maximumZoom = camera._scene.screenSpaceCameraController.maximumZoomDistance;
         var range = offset.range;
         if (!defined(range) || range === 0.0) {
             var radius = boundingSphere.radius;
-            if (radius === 0.0) {
-                offset.range = MINIMUM_ZOOM;
+            if(radius === 0) {
```
Comment (hpinkos) [inline Source/Scene/Camera.js]: Add back the space between `if` and `(`

File: Source/DataSources/EntityView.js [hunk 4]
```diff
@@ -317,9 +317,6 @@ define([
             var hasViewFrom = defined(viewFromProperty);
 
             if (!hasViewFrom && defined(boundingSphere)) {
-                var controller = scene.screenSpaceCameraController;
-                controller.minimumZoomDistance = Math.min(controller.minimumZoomDistance, boundingSphere.radius * 0.5);
```
Comment (hpinkos) [inline Source/DataSources/EntityView.js]: @mramato do you remember why this was added?

**Comment by hpinkos** [comment]
Other than that, everything looks fine to me.  All the tests pass locally.  I just want to hear from @mramato about this change in case that behavior was added for a reason

**Comment by burn123** [comment]
@hpinkos I committed the changes! # @

File: Source/DataSources/EntityView.js (hunk 4 above)
Comment (mramato) [inline Source/DataSources/EntityView.js]: Because our default minimumZoomDistance (at least at the time) was fairly large, so it was impossible to zoom to a model because you would end up 50 meters away.  What is the current default minimumZoomDistance?

Comment (burn123) [inline Source/DataSources/EntityView.js]: @mramato If no minimumZoom is specified, it goes to 1, and the flyTo will go to about 100 units away. But this problem is fixed by the clamping of the zoom to the `screenSpaceCameraController` minimum and maximum zoom.

**Comment by hpinkos** [comment]
Thanks @burn123!  This will be included in the 1.36 release, available tomorrow
