### PR TITLE
Creating tileset assumption fix

### LINKED ISSUE #3404: Create tileset with the tiles.json path
For #3241 

Currently when you create a `Cesium3DTileset` you pass in a url to the tileset folder. The code assumes the tiles json file is called `tiles.json`, which may not be true in all cases. 

We should support `options.url` to be either a directory of the tileset or a path to the tiles.json file. In either case, `this._url` should stay the directory of the tileset and `this._tilesJson` should stay the path to the tiles.json file.

This will help clean up the tileset tests which can't reuse files due to this limitation.

### PR DESCRIPTION
**Pull request by TomPed**
Fixes #3404

I believe this fixes the issue, could you take a look before I write some tests.

### CODE REVIEW

File: Source/Scene/Cesium3DTileset.js [hunk 1]
```diff
@@ -7,6 +7,9 @@ define([
         '../Core/destroyObject',
         '../Core/DeveloperError',
         '../Core/Event',
+        '../Core/getBaseUri',
+        '../Core/GetExtensionFromUri',
```
Comment (lilleyse) [inline Source/Scene/Cesium3DTileset.js]: Change to lowercase.

**Comment by lilleyse** [comment]
The code looks mostly good. There may be an issue if the url is given as a directory without a trailing slash, but you can check for that in the tests.

**Comment by pjcozzi** [comment]
Do you want to also address https://github.com/AnalyticalGraphicsInc/3d-tiles/pull/53#issue-126865190 in this PR?

**Comment by TomPed** [comment]
Updated.

File: Source/Scene/Cesium3DTileset.js [hunk 2]
```diff
@@ -68,10 +74,20 @@ define([
...
+        }
+
+        if ((url.lastIndexOf('/') !== (url.length - 1)) && (getExtensionFromUri(url) === '')) {
+            url = appendForwardSlash(url);
+        }
+        url = getBaseUri(url);
 
         this._url = url;
-        this._tilesJson = url + 'tiles.json';
+        this._tilesJson = url + fileName;
```
Comment (lilleyse) [inline Source/Scene/Cesium3DTileset.js]: I think this code can be cleaner. A structure like this might be better:

```javascript
var url;
var tilesJson;
if (getExtensionFromUri(url) === 'json') {
    // Set url and tilesJson
} else {
    // Set url and tilesJson
}
this._url = url;
this._tilesJson = tilesJson;
```

**Comment by TomPed** [comment]
Updated.

File: Source/Scene/Cesium3DTileset.js [hunk 3]
```diff
@@ -68,10 +74,19 @@ define([
...
 
-        url = appendForwardSlash(url);
+        var tilesJson;
+        if (getExtensionFromUri(url) === 'json') {
+            tilesJson = url;
+            url = getBaseUri(url);
+        } else {
+            if (url.lastIndexOf('/') !== (url.length - 1)) {
+                url = appendForwardSlash(url);
+            }
```
Comment (lilleyse) [inline Source/Scene/Cesium3DTileset.js]: You don't need to check for the trailing slash here because `appendForwardSlash` should handle that.

File: Source/Scene/Cesium3DTileset.js [hunk 4]
```diff
@@ -7,6 +7,9 @@ define([
         '../Core/destroyObject',
         '../Core/DeveloperError',
         '../Core/Event',
+        '../Core/getBaseUri',
+        '../Core/getExtensionFromUri',
+        '../Core/getFilenameFromUri',
```
Comment (lilleyse) [inline Source/Scene/Cesium3DTileset.js]: No need to include `getFilenameFromUri`anymore.

**Comment by TomPed** [comment]
If I don't check for the training slash and there already is one then I would have two slashes, wouldn't I?

**Comment by lilleyse** [comment]
`appendForwardSlash` handles that case.

**Comment by TomPed** [comment]
Oh, gotcha. That's cool.

**Comment by TomPed** [comment]
Updated.

**Comment by lilleyse** [comment]
I tweaked the test descriptions a little bit, but this is good to go. Merged.

**Comment by TomPed** [comment]
Thanks Sean
