### PR TITLE
Camera Fix

### LINKED ISSUE #3178: Fog dark
I experienced an issue with the fog when testing the 3d Models Sandcastle. This happens when I first orient the camera into the ground (horizon view), and then start zooming out.

fog-dark

### PR DESCRIPTION
**Pull request by lilleyse**
Fixes #3178 

Only the last change was required to fix the problem, but the others looked similar enough that I changed them too. Another approach is normalizing the direction, up, and right vectors in `Camera.updateMembers` to catch all cases of this happening, like:

```javascript
var direction = camera._direction;
var directionChanged = !Cartesian3.equals(direction, camera.direction);
if (directionChanged) {
    direction = Cartesian3.normalize(camera.direction, camera._direction);
}
```

### CODE REVIEW

**Comment by pjcozzi** [comment]
Update CHANGES.md.

Is it possible to add a reasonable test to verify that the vectors are orthonormal?

@bagnell merge when you are happy.

**Comment by lilleyse** [comment]
I believe that's already happening here: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Camera.js#L490-L506 but maybe the logic requires the vectors to be normalized before hand.

**Comment by lilleyse** [comment]
Oh.. do you mean a spec test?

**Comment by pjcozzi** [comment]
Yes, for the unit tests.

File: Specs/Scene/ScreenSpaceCameraControllerSpec.js [hunk 1]
```diff
@@ -507,7 +507,6 @@ defineSuite([
         moveMouse(MouseButtons.LEFT, startPosition, endPosition, true);
         updateController();
         expect(camera.position).toEqual(position);
-        expect(camera.direction).not.toEqual(Cartesian3.normalize(Cartesian3.negate(camera.position, new Cartesian3()), new Cartesian3()));
```
Comment (lilleyse) [inline Specs/Scene/ScreenSpaceCameraControllerSpec.js]: I removed this line because it wasn't actually doing anything. It only passed before because (0,0,-0.999999) did not equal (0,0,-1.0). Or maybe it should be checking `.toEqual` instead of `.not.toEqual`?
