### PR TITLE
Fixed Sandcastle console.log(null) crash

### LINKED ISSUE #3962: Sandcastle crashes on console.log(null)
The `console` tab in Sandcastle tries to display the value by calling `toString` on the value, and you can't `null.toString`

Reproduce with `console.log(null);` 

Reported on the forum: https://groups.google.com/forum/?hl=en#!topic/cesium-dev/bXrMbPjy7Ys

### PR DESCRIPTION
**Pull request by TomPed**
Fixes #3962.

Decided to use `Cesium.defined` for `CesiumSandcastle.js`. And added `null` check on the client side.

### CODE REVIEW

File: Apps/Sandcastle/Sandcastle-client.js [hunk 1]
```diff
@@ -5,7 +5,7 @@
     window.parent.postMessage('reload', '*');
 
     function defined(value) {
```
Comment (hpinkos) [inline Apps/Sandcastle/Sandcastle-client.js]: Why not use Cesium here as well?  Is it not defined in this scope?

Comment (TomPed) [inline Apps/Sandcastle/Sandcastle-client.js]: I believe that Cesium is not defined here yes.

**Comment by mramato** [comment]
`console.log(null)` should print null, it currently prints `undefined`.

**Comment by TomPed** [comment]
Updated.

**Comment by TomPed** [comment]
Updated.
