### PR TITLE
Fix shadowed models in 2D

### LINKED ISSUE #4378: Models crash in 2D
Open the 3D models Sandcastle example and switch to 2D.

### PR DESCRIPTION
**Pull request by bagnell**
Creates two sets of derived OIT commands when changing the scene mode is allowed. One for just OIT in 2D and one with OIT + shadows for 3D/CV.

Fixes #4378.

CC @pjcozzi @lilleyse

### CODE REVIEW

File: Source/Scene/OIT.js [hunk 1]
```diff
@@ -525,6 +527,9 @@ define([
         var framebuffer = passState.framebuffer;
         var length = commands.length;
 
+        var shadowsEnabled = scene.frameState.shadowHints.shadowsEnabled;
+        var scene2D = scene.mode === SceneMode.SCENE2D;
```
Comment (lilleyse) [inline Source/Scene/OIT.js]: You don't have to check for SCENE2D here - `scene.frameState.shadowHints.shadowsEnabled` will be false if the scene isn't 3D.

**Comment by lilleyse** [comment]
Tested and the code looks good to me, @pjcozzi do you want to take a look?

**Comment by pjcozzi** [comment]
@bagnell update CHANGES.md in master.
