### PR TITLE
fix crash due to undefined clipping planes texture

### LINKED ISSUE #6566: Intermittent clipping plane crash
tim 20180504171500

Possibly a case where `getClippingFunction` is called before `ClippingPlaneCollection` is updated?

@likangning93 would you be able to look into this?

Reported on the forum: https://groups.google.com/forum/#!topic/cesium-dev/mJ8NDsFrIhY

### PR DESCRIPTION
**Pull request by likangning93**
Fixes #6566

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Signed CLA is on file.

@likangning93, thanks for the pull request! Maintainers, we have a signed CLA from @likangning93, so you can review this at any time.

---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:

**Comment by likangning93** [comment]
Erm. I guess that's only "should fix" since I can't reproduce the specific behavior in that forum post/issue. So that's not great... but `getClippingFunction` definitely wasn't well-designed for this before, and this PR should help with that.

**Comment by likangning93** [comment]
I think there was a bug in here with partial texture updates for RGBA mode, and there wasn't a spec that caught it. I'll add a test.

Who wrote this... [hmmmm... ](https://github.com/AnalyticalGraphicsInc/cesium/pull/6201)

**Comment by likangning93** [comment]
@lilleyse this is ready for review now.

**Comment by lilleyse** [comment]
The code looks good and tests pass/demos work across browsers.

**Comment by lilleyse** [comment]
Just a side note - I haven't been able to reproduce the bug myself but I asked the forum member who posted the bug to test it out if he is able. I'll be good to merge until then or otherwise within the next couple of days.

**Comment by lilleyse** [comment]
@likangning93 there's a new error with the latest code: 

image

https://groups.google.com/forum/#!searchin/cesium-dev/mr.klien%7Csort:date/cesium-dev/mJ8NDsFrIhY/saLkI3lLAQAJ

File: Source/Scene/ClippingPlaneCollection.js [hunk 1]
```diff
@@ -665,6 +672,33 @@ define([
...
+    ClippingPlaneCollection.getTextureResolution = function(clippingPlaneCollection, context, result) {
+        var texture = clippingPlaneCollection.texture;
+        if (defined(texture)) {
+            result.x = texture.width;
+            result.y = texture.height;
+            return result;
+        }
+
+        var pixelsNeeded = ClippingPlaneCollection.useFloatTexture(context) ? clippingPlaneCollection.length : clippingPlaneCollection.length * 2;
+        var requiredResolution = computeTextureResolution(pixelsNeeded, result);
```
Comment (likangning93) [inline Source/Scene/ClippingPlaneCollection.js]: From the error message it looks like this might be returning `NaN` because `pixelsNeeded` is 0.
Don't know how that's happening though, because the clipping plane shader regen shouldn't be called in that case. Wish we were able to reproduce the error for debugging... I'll keep trying to trace this in the meantime.

**Comment by likangning93** [comment]
User on the forum provided a Sandcastle using the AGI HQ model and steps to reproduce:
[Sandcastle](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/#c=7VRNb5wwEP0rFhdA2hpWW0UVS1ZNtzlEitSojdpD6cELs7tWjI1sQ7qJ+t875iuQJofciyWwPfPevMcYGqZJw+EeNDknEu7JFgyvS/q93Qv8vF1ulbSMS9B+uM6kGw3iLBdgwM6B3WP1+bYLBo+ZJHjVWiRDypWSX8GoWudA91qVFwYTr4pg9WF1Fmbyz1ij1UBNDhJopXnJLW/AUFYUQV/bpfZpD0qVt2oacKNfUg2sON1gMW6A2iPIYF/L3HIlRwTppRLizOWCVxWXhxvBJBj0+HOIPl1T29P0YBpg2uKMyVUQ03hB3i3dPQ7dLMadcE77az2uB+n/KHm17lYJAZ2pxzlt1WGTZ7YW8ywoDvCDF/ZIkuVTpO3H2JRC5XUJ0tID2EsBbvrphM3LPA2lasAJyrzQNemyweA1Nxb7546S4Pmdvxjfe9hrfNkn7eguhAjG+q/XxmpvL/y/0S832lt4qbEnAZsu9pGXldLWfcMBpZGFEqug12hX53dOtzEOmUYDKC14Q3hxnnnPfh+Zh7qYMRjZ10J84w+QeRuS7mprlewg02NEWkbcrJThzm7is51Rorbgr62qkuX7uPq9FrC3STtDtg6fRh2nUzNlHw8KeQv3Wc+N6JE4jdDlzKxQrMA3/qUBLdgJ09PjcnPdbVJK0wiXA+ov)
1. remove
2. add
3. zoom in and out

**Comment by likangning93** [comment]
The Sandcastle was replacing the tileset's existing clipping plane collection with a new one, but some individual models were retaining references to the old clipping plane collection, which had been destroyed.

**Comment by lilleyse** [comment]
Ah good, that means https://github.com/AnalyticalGraphicsInc/cesium/issues/6599 is related.

**Comment by likangning93** [comment]
@lilleyse updated!

File: Source/Scene/Batched3DModel3DTileContent.js [hunk 2]
```diff
@@ -513,6 +513,12 @@ define([
             this._model._clippingPlanes = (tilesetClippingPlanes.enabled && this._tile._isClipped) ? tilesetClippingPlanes : undefined;
         }
 
+        // If the model references a destroyed ClippingPlaneCollection due to the tileset's collection being replaced with a
+        // ClippingPlaneCollection that gives this tile the same clipping status, update the model to use the new ClippingPlaneCollection.
+        if (defined(tilesetClippingPlanes) && defined(this._model._clippingPlanes) && this._model._clippingPlanes.isDestroyed()) {
```
Comment (lilleyse) [inline Source/Scene/Batched3DModel3DTileContent.js]: Alternatively could the check be `tilesetClippingPlanes !== this._model._clippingPlanes`?

Once https://github.com/AnalyticalGraphicsInc/cesium/issues/6599 is fixed we won't be destroying the collection anymore.

**Comment by likangning93** [comment]
@lilleyse updated!

File: Source/Scene/Instanced3DModel3DTileContent.js [hunk 3]
```diff
@@ -523,7 +523,7 @@ define([
 
             // If the model references a destroyed ClippingPlaneCollection due to the tileset's collection being replaced with a
```
Comment (lilleyse) [inline Source/Scene/Instanced3DModel3DTileContent.js]: Fix comment here as well.

Comment (likangning93) [reply Source/Scene/Instanced3DModel3DTileContent.js]: whoops

**Comment by likangning93** [comment]
@lilleyse ready!

**Comment by cesium-concierge** [comment]
Congratulations on closing the issue! I found these Cesium forum links in the comments above:

https://groups.google.com/forum/#!searchin/cesium-dev/mr

If this issue affects any of these threads, please post a comment like the following:

> The issue at https://github.com/AnalyticalGraphicsInc/cesium/pull/6576 has just been closed and may resolve your issue. Look for the change in the next stable release of Cesium or get it now in the master branch on GitHub https://github.com/AnalyticalGraphicsInc/cesium.
---

__I am a bot who helps you make Cesium awesome! [Contributions to my configuration are welcome.](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/.concierge)__

:earth_africa: :earth_americas: :earth_asia:
