### PR TITLE
Fixes #4444 - Rendering crashes with a 0 width LineRing clamped to ground

### LINKED ISSUE #4444: Rendering crashes with a 0 width LineRing clamped to ground: "Invalid array length"
I'm working with entities that must clamp to the terrain, and I found out that if I'm trying to render a 0 width linering clamped to the ground, I get a "Invalid array length" error

Attached is the kml file I was using when replicating the problem

[Composantes.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/538129/Composantes.zip)

### PR DESCRIPTION
**Pull request by erikmaarten**
- [x] support empty `PolylineGeometry`
- [x] support empty `CorridorGeometry`

Support for empty geometries seem to have already been implemented (in cba80f179ef1340ca481b636951c3cccfb64f34e) for most geometry types, including `CorridorGeometry`. See discussion in #4444.

### CODE REVIEW

**Comment by erikmaarten** [comment]
Ready for review. (See discussion in #4444)

**Comment by erikmaarten** [comment]
@mramato Could you review?

File: Specs/Core/PolylineGeometrySpec.js [hunk 1]
```diff
@@ -31,13 +31,13 @@ defineSuite([
         }).toThrowDeveloperError();
     });
 
-    it('constructor throws with invalid width', function() {
+    it('constructor does not throw with invalid width', function() {
```
Comment (mramato) [inline Specs/Core/PolylineGeometrySpec.js]: Rather than changing this text not to throw, we should instead delete this test and add a test where `PolylineGeometry.createGeometry` is called and returns undefined.  Basically, copy `constructor computes all vertex attributes` around line 52 and change width to -1, then remove all the expects except for `line` to be undefined.

File: Source/Core/PolylineGeometry.js [hunk 2]
```diff
@@ -309,9 +309,11 @@ define([
         var k;
 
         var positions = arrayRemoveDuplicates(polylineGeometry._positions, Cartesian3.equalsEpsilon);
-
         var positionsLength = positions.length;
-        if (positionsLength < 2) {
+
+        // A width of a pixel or less is not a valid geometry, but in order to support external data
+        // that may have errors we treat this as an empty geometry.
+        if (positionsLength < 2 || width < 1.0) {
```
Comment (mramato) [inline Source/Core/PolylineGeometry.js]: @bagnell can confirm, but I think less than 1 is fine, it just needs to be greater than 0.

File: Source/Core/CorridorGeometry.js [hunk 3]
```diff
@@ -679,8 +679,8 @@ define([
 
     function computeRectangle(positions, ellipsoid, width, cornerType) {
         var cleanPositions = arrayRemoveDuplicates(positions, Cartesian3.equalsEpsilon);
-        var length = cleanPositions.length - 1;
-        if (length === 0 || width === 0) {
+        var length = cleanPositions.length;
```
Comment (mramato) [inline Source/Core/CorridorGeometry.js]: How hard is it to write a test for the updated code in this function.  One option would be exposing `computeRectangle` as a private `CorridorGeometry._computeRectangle` so that it can be tested directly.

CC @hpinkos

**Comment by mramato** [comment]
One other thing I noticed is that when width is 0 and we pass `clampToGround:true` when loading the KML, the bounding sphere is way too big.  This problem goes away if width is greater than 0.  @hpinkos any ideas here?  We can always open a separate issue if it's an unrelated problem.

Just those three comments, definitely fixes the issue.  Thanks.

File: Source/Core/CorridorGeometry.js (hunk 3 above)
Comment (mramato) [inline Source/Core/CorridorGeometry.js]: OK, please write up an issue so we don't forget about it.

**Comment by hpinkos** [comment]
> One other thing I noticed is that when width is 0 and we pass clampToGround:true when loading the KML, the bounding sphere is way too big

The bounding sphere for all the entities in the KML?  I didn't run the code to see, but I'm guessing this is because we return a Rectangle(0, 0, 0, 0) when there is no geometry and the bounding sphere tries to include the point at 0, 0.  Do you have a code sample handy to look at this? Either way, I'm confident it's an unrelated problem

**Comment by mramato** [comment]
> The bounding sphere for all the entities in the KML? I didn't run the code to see, but I'm guessing this is because we return a Rectangle(0, 0, 0, 0) when there is no geometry and the bounding sphere tries to include the point at 0, 0. Do you have a code sample handy to look at this? Either way, I'm confident it's an unrelated problem

The bounding sphere should be undefined for the corridor geometry if it fails to compute.  All you have to do it load the example KML from #4444 with `clampToGround` set to true in the KML options.  The flight will be different than when it's false (the default)

File: Source/Core/PolylineGeometry.js (hunk 2 above)
Comment (hpinkos) [inline Source/Core/PolylineGeometry.js]: You might be right.  The Polyline primitive works with a width of 0.5, I don't see why the PolylineGeometry wouldn't.  @erikmaarten try changing this to <= 0 and see what happens.  Here's a code example so you can see what the Polyline primitive looks like:
``` javascript
var viewer = new Cesium.Viewer('cesiumContainer');
var collection = viewer.scene.primitives.add(new Cesium.PolylineCollection());
collection.add({
    positions : Cesium.Cartesian3.fromDegreesArrayHeights([-75, 35, 100000, -85, 35, 100000]),
    width : 0.5
});
```

**Comment by hpinkos** [comment]
> The bounding sphere should be undefined for the corridor geometry if it fails to compute

Yeah, what I thought was happening is true.  `computeRectangle` can't return `undefined` because `GroundPrimitive` crashes, and whatever function in `GroundPrimitive` that converts that rectangle to a bounding sphere is adding a bounding sphere at (0, 0) that contributes to the KML bounding sphere.  `GroundPrimitive` needs to handle empty geometry better.

**Comment by mramato** [comment]
> Yeah, what I thought was happening is true. computeRectangle can't return undefined because GroundPrimitive crashes, and whatever function in GroundPrimitive that converts that rectangle to a bounding sphere is adding a bounding sphere at (0, 0) that contributes to the KML bounding sphere. GroundPrimitive needs to handle empty geometry better.

OK, please write an issue for this as well.  Sounds like something we should look at soonish, since lots of KML data has bad geometry.

File: Source/Core/PolylineGeometry.js (hunk 2 above)
Comment (erikmaarten) [inline Source/Core/PolylineGeometry.js]: A line of width 0.5 works fine and is indeed thinner than a line of width 1.0. Changed this in new commit.

File: Specs/Core/PolylineGeometrySpec.js (hunk 1 above)
Comment (erikmaarten) [inline Specs/Core/PolylineGeometrySpec.js]: Fixed

**Comment by erikmaarten** [comment]
Comments addressed, I think I got everything that's within the scope for this PR. Please review.

**Comment by erikmaarten** [comment]
@mramato @hpinkos This is ready

**Comment by mramato** [comment]
@hpinkos please merge this if you're happy.  Thanks.

**Comment by hpinkos** [comment]
Looks good to me, thanks @erikmaarten!
