### PR TITLE
fix ground polygon rectangles

### LINKED ISSUE #7507: Ground polygon is wrong
image

The red is a polygon with height: 0.  The purple is where it overlaps with the ground polygon.

```js
var viewer = new Cesium.Viewer('cesiumContainer');

viewer.entities.add({
    polygon : {
        hierarchy : Cesium.Cartesian3.fromDegreesArray([-120.0, 30.0,
                                                        -80.0, 30.0,
                                                        -80.0, 40.0,
                                                        -120.0, 40.0]),
        material : Cesium.Color.BLUE.withAlpha(0.5)
    }
});

viewer.entities.add({
    polygon : {
        hierarchy : Cesium.Cartesian3.fromDegreesArray([-120.0, 30.0,
                                                        -80.0, 30.0,
                                                        -80.0, 40.0,
                                                        -120.0, 40.0]),
        material : Cesium.Color.RED.withAlpha(0.5),
        height: 0
    }
});

viewer.zoomTo(viewer.entities);
```

### PR DESCRIPTION
**Pull request by likangning93**
Fixes #7507. The previous algorithm for computing rectangles in `PolygonGeometry` didn't take the arctype between points into account. Cesium uses these rectangles to prevent batched ground geometries from drawing on each other using a fragment discard, which was why some ground polygons were getting cut off.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @likangning93!
* :heavy_check_mark: Signed CLA found.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

File: Source/Core/PolygonGeometry.js [hunk 1]
```diff
@@ -372,18 +376,84 @@ define([
...
+        }
+
+        return result;
+    }
+
+    var interpolatedCartographicScratch = new Cartographic();
+    function interpolateAndGrowRectangle(startCartographic, endCartographic, ellipsoid, arcType, inverseChordLength, result, idlCross) {
+        var segmentPath;
+        if (arcType === ArcType.GEODESIC) {
+            segmentPath = new EllipsoidGeodesic(startCartographic, endCartographic, ellipsoid);
```
Comment (hpinkos) [inline Source/Core/PolygonGeometry.js]: Move `EllipsoidGeodesic` and `EllipsoidRhumbLine` outside the function scope so it can be reused, similarly to https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/PolylinePipeline.js#L110

File: Source/Core/PolygonGeometry.js [hunk 2]
```diff
@@ -372,18 +376,84 @@ define([
...
+        } else {
+            segmentPath = new EllipsoidRhumbLine(startCartographic, endCartographic, ellipsoid);
```
Comment (hpinkos) [inline Source/Core/PolygonGeometry.js]: If it's using Rhumb lines, can't we use the previous logic of `return Rectangle.fromCartesianArray(positions, ellipsoid, result);` instead of iterating through the entire arc?

**Comment by hpinkos** [comment]
Just those comments.  Thanks for getting to this so quickly @likangning93 !

**Comment by likangning93** [comment]
@hpinkos this is up-to-date

**Comment by hpinkos** [comment]
Great work, @likangning93!
