### PR TITLE
Fix pick with skyatmosphere

### LINKED ISSUE #4783: Picking near Earth sphere border returns pickIds equal to 255, 65535 which is being misinterpreted as object pick
Take a look at the [following example](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Hello%20World.html&label=Showcases&gist=961346e4535e7caf3a780acefc2f1e10):

```js
Cesium.Camera.DEFAULT_VIEW_RECTANGLE = Cesium.Rectangle.fromDegrees(-40, -40, 40, 40);

var viewer = new Cesium.Viewer('cesiumContainer', {
    selectionIndicator : false,
    infoBox : false
});

var scene = viewer.scene;
var handler;

var i;
for (i = 0; i != 255; ++i) {
    viewer.entities.add({
        id: 'obj_' + i,
        /*
        polyline: {
            positions: Cesium.Cartesian3.fromDegreesArray(
                [Math.random() * 10, Math.random() * 10, Math.random() * 10, Math.random() * 10]),
            followSurface: false,
            material: Cesium.Color.RED,
          },
        */
        point: {
            color: Cesium.Color.RED
        },
        position: Cesium.Cartesian3.fromDegrees(Math.random() * 10, Math.random() * 10)
    });
}

handler = new Cesium.ScreenSpaceEventHandler(scene.canvas);
handler.setInputAction(function(movement) {
    var pickedObject = scene.pick(movement.endPosition);
    if (Cesium.defined(pickedObject)) {
        var cartesian = viewer.camera.pickEllipsoid(movement.endPosition, scene.globe.ellipsoid);
        if (cartesian) {
            var cartographic = Cesium.Cartographic.fromCartesian(cartesian);
            var longitudeString = Cesium.Math.toDegrees(cartographic.longitude).toFixed(2);
            var latitudeString = Cesium.Math.toDegrees(cartographic.latitude).toFixed(2);
            
            console.log(pickedObject.id._id + ' ' + movement.endPosition + ' (' + longitudeString + ', ' + latitudeString + ')');
        } else {
            console.log(pickedObject.id._id + ' ' + movement.endPosition);
        }
    }
}, Cesium.ScreenSpaceEventType.MOUSE_MOVE);
```

It displays points in [0, 10]x[0, 10] degrees square and on mouse move tries to pick entity under mouse cursor --- if there is any, outputs mouse coordinates in the log.

Since all points in [0, 10]x[0, 10] degrees square it is expected that points will be picked only in it, which is not the case --- if I move mouse near Earth sphere border I get some points selected:

(notice that last two columns in the log are selected point coordinates, and they are far outside [0, 10]x[0, 10] degrees square).

Same issue with polylines entities picking (and probably other entities types).

If I reduce number of entities to 253 or less I can't reproduce this issue.

Tested in CesiumJS 1.28 in Firefox Developer Edition 52.0a2 and Chromium 55.0.2883.87 on Ubuntu 16.04 with NVidia GTX 980 with NVidia proprietary drivers 367.57.

### PR DESCRIPTION
**Pull request by rutsky**
Add raising `DeveloperError` if previously picked object is picked again in `drillPick`.
Don't draw SkyAtmosphere when picking.

Fixes #4783 and #4784.

### CODE REVIEW

**Comment by rutsky** [comment]
Please review changes thoroughly --- I'm not familiar with CesiumJS internals.

**Comment by rutsky** [comment]
What is expected pickId when picking not-object (stars, Earth tiles)? Shouldn't [Context.getObjectByPickColor](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Renderer/Context.js#L1119) get zero color for anything but not object?

Because I see that [Context.getObjectByPickColor](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Renderer/Context.js#L1119) gets colors like the following:

```
4278190338
4278190081
4278255873
4278190081
4278190338
```

**Comment by hpinkos** [comment]
Thanks @rutsky!  Most of the team is out of the office this week, but we'll try review this soon.

File: Source/Scene/Scene.js [hunk 1]
```diff
@@ -2731,7 +2732,16 @@ define([
                 pickedPrimitives.push(primitive);
             }
 
+            prevPickedResult = pickedResult;
             pickedResult = this.pick(windowPosition);
+
+            //>>includeStart('debug', pragmas.debug);
+            if (pickedResult === prevPickedResult) {
+                throw new DeveloperError(
```
Comment (pjcozzi) [inline Source/Scene/Scene.js]: This would mask a bug elsewhere - basically setting a primitive's `show` to `false` not working.  Can you remove this and keep the scope of this bug to picking the atmosphere?

**Comment by pjcozzi** [comment]
@rutsky usually we would add a new test, but it will be hard to reasonably do so without tightly coupling the test to the engine code so don't worry about it.

**Comment by pjcozzi** [comment]
> What is expected pickId when picking not-object (stars, Earth tiles)?

Looking at the sky box, sun, and moon `update` functions they do not generate pick commands so they should not be pickable (they are handled outside our normal command processing so the color commands are still being executed in the pick pass, which is the problem).

The globe tiles won't generate any pick commands, other than writing depth, but they are processed in the right place so they are unlikely to be an issue.

I can finish this PR up next week if that is OK with you.  Just address https://github.com/AnalyticalGraphicsInc/cesium/pull/4790#discussion_r94083659 in the meantime, please.

File: Source/Scene/Scene.js (hunk 1 above)
Comment (rutsky) [inline Source/Scene/Scene.js]: I excluded commit with adding `DeveloperError` from the pull request.

Are you sure there is no benefit in adding such internal consistency check? (I can open second PR with this change.)
IMO this check costs almost nothing, but can improve debugging experience next time when pick issue will arise.

**Comment by rutsky** [comment]
> I can finish this PR up next week if that is OK with you. Just address #4790 (comment) in the meantime, please.

Thanks, @pjcozzi , it's better if you finish this PR, since it requires deeper knowledge of Cesium internals that I have, plus it's holidays here in Russia next week.

I removed commit with consistency check --- see my comment.

**Comment by pjcozzi** [comment]
This comment, https://github.com/AnalyticalGraphicsInc/cesium/issues/4783#issuecomment-270386401, was meant for this PR:

> Thanks again for the fix, @rutsky. I made a small tweak to also not render the sun, moon, and sky box and merged everything in #4806 since I could not commit to your branch (could have been an issue on my end).
